### ISSUE TITLE
Endless retrying when using snmpv3 with privkey and retries set to 1

### ISSUE THREAD

**Issue by tvestelind** [etingof/pysnmp#101]
I've run into an issue where my SNMPv3 request doesn't timeout even though the timeout is set to 5 and the number of retries is set to 1.

Steps to reproduce:
1. Download [endless_loop.txt](https://github.com/etingof/pysnmp/files/1434241/endless_loop.txt), rename it to `endless_loop.py` and install pysnmp (I've tested with 4.4.1)
2. Download [1.3.6.1.6.1.1.0.txt](https://github.com/etingof/pysnmp/files/1434247/1.3.6.1.6.1.1.0.txt) and rename it to `1.3.6.1.6.1.1.0.snmprec`
3. Go to the folder where you downloaded the `.snmprec` file and run `docker run --rm --name=endless_loop -v $PWD:/usr/share/snmpsim/data -p 161:161/udp -e EXTRA_FLAGS="--v3-user testing --v3-auth-key authkey1234 --v3-auth-proto SHA --v3-priv-key privkey1234 --v3-priv-proto AES" tvestelind/snmpsim`. This will start a docker container with `snmpsimd` and SNMPv3 configured
4. Run `chmod +x endless_loop.py`
5. Run `docker exec -it enless_loop ip a` to get the ip address
6. Run `./endless_loop.py <ip_address> privkey1234`, it should print some info
7. Run `./endless_loop.py <ip_address> badkey1234`, __it will loop endlessly but it shouldn't, right?__
8. Run `./endless_loop.py <ip_address> badkey1234 --retries=2`, setting number of retries to 2 makes it terminate

I don't have time to debug it right now but I might give a try later.

Cheers,
Tomas

**Comment by etingof** [comment]
Thank you for your report!

Here is [my first take](https://github.com/etingof/pysnmp/pull/106) on the problem. I'd appreciate your tests. ;-)

**Comment by etingof** [comment]
Merged. Thank you!
