### ISSUE TITLE
ObjectType's with MIB resolution disabled

### ISSUE THREAD

**Issue by jof** [etingof/pysnmp#111]
I'm working with pysnmp and a vendor device without a MIB.
I would like to just SNMP get some OIDs with SNMPv2 and do some things with the result values.

I'm currently getting this to work by using `pysnmp.entity.rfc3413.oneliner.cmdgen.MibVariable(numeric_dotted_oid_string)` to make an `ObjectIdentity`. I then pass a list of these `ObjectIdentity`'s to a `pysnmp.entity.rfc3413.oneliner.cmdgen.CommandGenerator.getCmd` with the kwarg `lookupMib` set to False.
However, this code path still seems to trigger some MIB resolution to resolve names, which is taking a big performance hit.

Is there some simple way to get get an OID without engaging any kind of MIB loading or resolution?

**Comment by jof** [comment]
I've also tried manually creating an `ObjectType` from an `ObjectIdentity` formed from an OID string and a base SNMP type.
However, anything that seems to use this `ObjectType` runs into an error about the object not being fully resolved. 

Is there maybe a path towards constructing my own `ObjectType`s which are "fully resolved"?

**Comment by jof** [comment]
Here's a minimal example to show the confusion I am having:

```
#!/usr/bin/env python
from __future__ import print_function
from pysnmp.hlapi import getCmd
from pysnmp.hlapi import ObjectType
from pysnmp.hlapi import ObjectIdentity
from pysnmp.hlapi import UdpTransportTarget
from pysnmp.hlapi import CommunityData
from pysnmp.hlapi import SnmpEngine

single_oid = ObjectType(ObjectIdentity('1.3.6.1.4.1.31973.1.2.3.4.5'))
community = "public"
hostname = "demo.snmplabs.com"
port = 161
errorIndication, errorStatus, errorIndex, varBinds = next(getCmd(
    SnmpEngine(),
    CommunityData(community),
    UdpTransportTarget((hostname, port)),
    *single_oid,
    lookupMib=False
))
print(repr(varBinds))
```

And running this yields for me:
```
jof@hostname ~/tmp % python snmp_wtf.py
Traceback (most recent call last):
  File "snmp_wtf.py", line 19, in <module>
    lookupMib=False
  File "/home/jof/.local/lib/python2.7/site-packages/pysnmp/smi/rfc1902.py", line 708, in __getitem__
    raise SmiError('%s object not fully initialized' % self.__class__.__name__)
pysnmp.smi.error.SmiError: ObjectType object not fully initialized
```

Library versions:
```
jof@hostname ~/tmp % pip freeze | grep -E '^(pysmi|pysnmp|pyasn1)'
pyasn1==0.4.2
pyasn1-modules==0.0.8
pysmi==0.2.2
pysnmp==4.4.2
pysnmp-mibs==0.1.6
```


From what I can gather from skimming some of the `pysnmp.smi` libraries, it seems to really want to resolve this OID with MIB (which is what I want to avoid, as there isn't one). I can only guess this is so that it can determine a proper type conversion for any results?
Ideally, I would want to get pysnmp to just examine the response to determine the type, just like Net-SNMP does.

**Comment by jof** [comment]
Ok.... this is my fault.
By passing in single_oid as a single ObjectType with a splat operator ("*"), it was trying to unpack the ObjectType, rather than using it as a list of objects to get.

By casting the `single_oid` to a `[single_oid]` or removing the `*` gets this working again.

**Comment by etingof** [comment]
> By casting the single_oid to a [single_oid] or removing the * gets this working again.

You totally nailed it! Sorry for getting back to this too late. ;-)

Feel free to re-open this issue if its not fully resolved.
