### ISSUE TITLE
demo agent lists config for unsupported auth protocol / inconsistent naming

### ISSUE THREAD

**Issue by rstory** [etingof/pysnmp#116]
<http://snmplabs.com/snmpsim/public-snmp-agent-simulator.html> lists

`usr-sha384-aes256 | SHA2 (384/512bit) | authkey1 | AES (256bit) | privkey1`

But sha384 is not a supported. snmpget.py help reports:

`  -a AUTH-PROTOCOL  authentication protocol (MD5|NONE|SHA|SHA128|SHA192|SHA256|SHA512|SHA96)`

and trying to use SHA384:

```
snmpget.py -r 0 -v 3 -u usr-sha384-aes256 -x AES256 -X privkey1 -a SHA384 -A authkey1 -l authPriv 127.0.0.1:1161 sysContact.0
Error: Unknown authentication protocol "SHA384
```

I'm guessing that the config should be for **usr-sha512-aes256**.

Also, the previous line:

`usr-sha256-3des | SHA2 (128/224bit)`

doesn't make sense. 128/224 bits is usmHMAC128SHA224AuthProtocol so the name should be usr-sha224-3des.

It's all a bit confusing because in some cases you are using the key length and in others you are using the mac length.  It really should be "SHA224|SHA256|SHA384|SHA512" or "SHA128|SHA192|SHA256|SHA384". I'd suggest the former, as those are the SHA algorithms defined in RFC 6234 <https://tools.ietf.org/html/rfc6234> (and the key lengths). Mixing them is confusing, especially for SHA256, which could be the key length (256/192) or the mac length (384/256).

Both Net-SNMP and SNMP Research use the "SHA224|SHA256|SHA384|SHA512" forms.

**Comment by etingof** [comment]
Hopefully straightened everywhere, including [public SNMP simulator](http://snmplabs.com/snmpsim/public-snmp-agent-simulator.html#snmpv3-usm-users) and [pysnmp-apps](https://github.com/etingof/pysnmp-apps/archive/master.zip). Feel free to re-open this issue if you encounter further mess.

Thank you! ;-)
