### ISSUE TITLE
How handle nosuchname?

### ISSUE THREAD

**Issue by sergey-gt-ekb** [etingof/pysnmp#117]
Hello, @etingof !

I do getnext request via v1. And got response `noSuchName` with index 2:

```
16:45:59.518182 IP (tos 0x0, ttl  61, id 0, offset 0, flags [DF], proto: UDP (17), length: 105) 10.45.0.111.snmp > 10.74.0.6.12326: [udp sum ok]  { SNMPv1 C=****** { GetResponse(60) R=14357445  noSuchName@2 .1.3.6.1.2.1.31.1.1.1.19= .1.3.6.1.2.1.2.2.1.10= .1.3.6.1.2.1.2.2.1.16= } }
```

In that case, I normally delete from request invalid oid and repeat request. But pysnmp return 3 end_of_mib vars and I cannot determine what oid is invalid.

Response tuple:

```
None, noError, 0,
[
  [
    (
      <ObjectName value object at 0xb72e516c tagSet <TagSet object at 0xb759d02c tags 0:0:6> payload [1.3.6.1.2.1.31.1.1.1.19]>,
      <EndOfMibView value object at 0xb75b986c subtypeSpec <ConstraintsIntersection object at 0xb7599eec consts <SingleValueConstraint object at 0xb7599e2c consts b''>> tagSet <TagSet object at 0xb75b990c tags 128:0:2> encoding iso-8859-1 payload [No more variable...in this MIB View]>
    ), 
    (
      <ObjectName value object at 0xb72e59cc tagSet <TagSet object at 0xb759d02c tags 0:0:6> payload [1.3.6.1.2.1.2.2.1.10]>,
      <EndOfMibView value object at 0xb75b986c subtypeSpec <ConstraintsIntersection object at 0xb7599eec consts <SingleValueConstraint object at 0xb7599e2c consts b''>> tagSet <TagSet object at 0xb75b990c tags 128:0:2> encoding iso-8859-1 payload [No more variable...in this MIB View]>
    ),
    (
      <ObjectName value object at 0xb72e58cc tagSet <TagSet object at 0xb759d02c tags 0:0:6> payload [1.3.6.1.2.1.2.2.1.16]>,
      <EndOfMibView value object at 0xb75b986c subtypeSpec <ConstraintsIntersection object at 0xb7599eec consts <SingleValueConstraint object at 0xb7599e2c consts b''>> tagSet <TagSet object at 0xb75b990c tags 128:0:2> encoding iso-8859-1 payload [No more variable...in this MIB View]>
    )
  ]
]
```

**Comment by etingof** [comment]
When SNMP v1 response has `error-status` raised and `error-index` pointing to the problem OID in the *request*, there is no guarantee that the rest of OIDs in response are indeed in good shape. Therefore when you get SNMP v1 response with `error-status` you can't do much but discard everything you got in response. That is the reason why pysnmp sets `endOfMib` sentinel to all the values in the response.

Could you remove the OID from the request which is indicated by the `error-index` value in response prior to retrying the request once again?

**Comment by sergey-gt-ekb** [comment]
I have not get an error status and/or error-index, a get all vars set to endOfMibView.
I got response tuple: None, noError, 0, [endOfMibView vars...].
I cannot determinate the index of noSuchName.
But response is have what index:
{
   SNMPv1 C=******
  {
  GetResponse(60) R=14357445  noSuchName@2
    .1.3.6.1.2.1.31.1.1.1.19=
    .1.3.6.1.2.1.2.2.1.10=
    .1.3.6.1.2.1.2.2.1.16= 
  }
}
Sorry for my english.

**Comment by etingof** [comment]
Ah, you are right! The missing `error-status` & `error-index` fields should now be preserved since commit e81dfd5f8a29bc10037429e55b0beeec66114927.  You are welcome to try it out. ;)

**Comment by sergey-gt-ekb** [comment]
Thanks a lot!
