### ISSUE TITLE
SNMP INFORM acknowledgment

### ISSUE THREAD

**Issue by jigarshahindia** [etingof/pysnmp#121]
I want my application have a control over acknowledgment of trap .
My sender are using inform . 
But i need my reciever to acknowledgment .
Can someOne help iwith small snapshot of code how it can be done using pysnmp

**Comment by etingof** [comment]
If your goal is to receive SNMP INFORM message and acknowledge its reception back to the SNMP client, [this example code](http://snmplabs.com/pysnmp/examples/v3arch/asyncore/manager/ntfrcv/snmp-versions.html#serving-multiple-network-interfaces) should do it.

You may only want to strip off one of the ports this script is listening at.

**Comment by jigarshahindia** [comment]
Hey ,
Thanx for the reply.
I didn't get how should I reply sender saying hey I received the message. 
The link to code which you shared, currently I have same code running. But what should my callback function return for acknowledgment?

**Comment by etingof** [comment]
I believe your callback should not return anything. The pysnmp itself [will return](https://github.com/etingof/pysnmp/blob/master/pysnmp/entity/rfc3413/ntfrcv.py#L82) the variable-bindings it received in request back to the sender is it [is required by the RFC](https://tools.ietf.org/html/rfc3413#page-17).
