### ISSUE TITLE
Segmentation Fault, while Fetching sysDescr using snmp v3 authpriv sha-aes128

### ISSUE THREAD

**Issue by raju2b** [etingof/pysnmp#122]
Segmentation Fault is coming while trying to fetch sysDescr using SNMP v3 authpriv  sha-aes128
Priv:
md5-des is working fine
sha-aes128 is causing segementation fault, is it a known issue or i am doing something wrong ?
Below is the **code snippet** :
```
from pysnmp.hlapi import *
from pysnmp import debug
debug.setLogger(debug.Debug('all'))

errorIndication, errorStatus, errorIndex, varBinds = next(
    getCmd(SnmpEngine(),
           UsmUserData('usr-sha-aes128', 'authkey1', 'privkey1',
                       authProtocol=usmHMACSHAAuthProtocol,
                       privProtocol=usmAesCfb128Protocol),
           UdpTransportTarget(('demo.snmplabs.com', 161)),
           ContextData(),
           ObjectType(ObjectIdentity('1.3.6.1.2.1.1.1')))
)

if errorIndication:
    print(errorIndication)
elif errorStatus:
    print('%s at %s' % (errorStatus.prettyPrint(),
                        errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
else:
    for varBind in varBinds:
        print(' = '.join([x.prettyPrint() for x in varBind]))
```

Attached the logs.
[SEGV_aes128_logs.txt](https://github.com/etingof/pysnmp/files/1591225/SEGV_aes128_logs.txt)

**Comment by etingof** [comment]
This definitely has nothing to do with pysnmp. It does not introduce any machine level code which can segfault.

I'd point my finger in the direction of the [pycryptodome](https://github.com/Legrandin/pycryptodome), but before you submit an issue there make sure you are using the latest pycryptodomex package and the latest pysnmp.
