### ISSUE TITLE
Walking on table

### ISSUE THREAD

**Issue by nadavishe** [etingof/pysnmp#131]
Hi, Ilya
I'm trying to walk on some node in my custom MIB
Fo example, here is properties of such node
####################################################
Name:	rimModuleName
Type:	OBJECT-TYPE
OID:	1.3.6.1.4.1.15921.20.4.1.1.1
Full path:	iso(1).org(3).dod(6).internet(1).private(4).enterprises(1).ma(15921).maGEN2(20).maRIM(4).maRimTable(1).maRimEntry(1).rimModuleName(1)
Module:	MaGEN2-MIB

Parent:	maRimEntry
Next sibling:	rimZoneInfo

Numerical syntax:	Octets
Base syntax:	OCTET STRING
Composed syntax:	OCTET STRING
Status:	current
Max access:	read-write
Size list:	1: 0..45

Description:	RIM Module Name
########################################################
There are few instances under this leaf - in format 0.0

I wrote:

***errorIndication,errorStatus,errorIndex,varBinds = next(getCmd(SnmpEngine(),
                          CommunityData('public'),
                          UdpTransportTarget(('10.208.255.73', 161)),
                          ContextData(),
                          ObjectType(ObjectIdentity('1.3.6.1.4.1.15921.20.4.1.1.1','0.0'))))***

But i get error:

***pysnmp.smi.error.MibNotFoundError: 1.3.6.1.4.1.15921.20.4.1.1.1 compilation error(s): missing***

Please help me to understand what is wrong here? Thanks

**Comment by etingof** [comment]
I believe the problem here is that you pass `ObjectIdentity` two parameters what makes it interpreting them as MIB::symbol. If you want to pass it just an OID, then do it like this:

    ObjectType(ObjectIdentity('1.3.6.1.4.1.15921.20.4.1.1.1.0.0'))))

Here's [the doc](http://snmplabs.com/pysnmp/docs/api-reference.html#pysnmp.smi.rfc1902.ObjectIdentity).

**Comment by nadavishe** [comment]
Hello, Ilya

Thank you for your quick response, all is OK now

I have another 2 questions:


  1.  I don’t find example how to get traps
  2.  I don’t success to set variables with setCmd

errorIndication, errorStatus, errorIndex, varBinds = next(
    setCmd(SnmpEngine(),
           CommunityData('private'),
           UdpTransportTarget(('10.208.255.73', 162)),
           ContextData(),
           ObjectType(ObjectIdentity('1.3.6.1.4.1.15921.20.23.1.1.1.15.1.1.1'),'abc'))
)

I receive:

pysnmp.smi.error.SmiError: MIB object ObjectIdentity('SNMPv2-SMI', 'enterprises', '15921.20.23.1.1.1') is not OBJECT-TYPE (MIB not loaded?)


Thanks

Nadav Chernin
Automation Technical Team Leader

Golan Building, Hagolan street & Hanegev street
Airport City, Israel 70151
Corning Optical Communications Wireless LTD

Office: (972) 8.9183.914  I  Mobile: (972) 50.4172213
CherninN@corning.com<mailto:CherninN@corning.com>
