### ISSUE TITLE
Implement custom mib snmp agent

### ISSUE THREAD

**Issue by diegovm2** [etingof/pysnmp#134]
Hi, Ilya

A few months ago I asked for help on stackoverflow and you told me that I should post here to have more hands-on help with the code. The help you provided back then was very useful, I thank you very much. I implemented some tables succesfully, but I still have some errors with other tables. 

This is the first try, [using as an example](http://snmplabs.com/pysnmp/examples/v3arch/twisted/agent/cmdrsp/agent-side-mib-implementations.html):

```
rowInstanceId = characterEntry.getInstIdFromIndices(2)
        mibInstrumentation = self._snmpContext.getMibInstrum()
        mibInstrumentation.writeVars(
            ((characterNumber.name + rowInstanceId, 12),
             (characterWidth.name + rowInstanceId, 13), 
             (characterBitmap.name + rowInstanceId, 5)    
            )
        )
```

The mib was imported and looks like this

```
characterTable = MibTable((1, 3, 6, 1, 4, 1, 1206, 4, 2, 3, 3, 4), )
if mibBuilder.loadTexts: characterTable.setStatus('mandatory')
characterEntry = MibTableRow((1, 3, 6, 1, 4, 1, 1206, 4, 2, 3, 3, 4, 1), ).setIndexNames((0, "DMS-MIB", "fontIndex"), (0, "DMS-MIB", "characterNumber"))
if mibBuilder.loadTexts: characterEntry.setStatus('mandatory')
characterNumber = MibTableColumn((1, 3, 6, 1, 4, 1, 1206, 4, 2, 3, 3, 4, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 65535))).setMaxAccess("readonly")
if mibBuilder.loadTexts: characterNumber.setStatus('mandatory')
characterWidth = MibTableColumn((1, 3, 6, 1, 4, 1, 1206, 4, 2, 3, 3, 4, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 255))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: characterWidth.setStatus('mandatory')
characterBitmap = MibTableColumn((1, 3, 6, 1, 4, 1, 1206, 4, 2, 3, 3, 4, 1, 3), OctetString()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: characterBitmap.setStatus('mandatory')
```

This is the error I get and I can't track it source. I am running other tables with the same form and they do work. 

```
Traceback (most recent call last):
  File "dms_agent.py", line 996, in <module>
    agent = SNMPAgent(objects)
  File "dms_agent.py", line 732, in __init__
    (characterBitmap.name + rowInstanceId, 5)    
  File "/usr/local/lib/python2.7/dist-packages/pysnmp/smi/instrum.py", line 256, in writeVars
    return self.flipFlopFsm(self.fsmWriteVar, varBinds, acInfo)
  File "/usr/local/lib/python2.7/dist-packages/pysnmp/smi/instrum.py", line 239, in flipFlopFsm
    raise origExc
pysnmp.smi.error.SmiError: Short OID for index Integer32(subtypeSpec=ConstraintsIntersection(ValueRangeConstraint(-2147483648, 2147483647), ValueRangeConstraint(1, 65535)))
```

I also have some problems implementing scalars that are not Integer.  I override the readGet() function, and get the following error. 

```
;  File "dms_agent.py", line 531, in readGet
    return name, self.getSyntax().clone(getValue())
;TypeError: 'str' object is not callable
```

If you have time to run the program yourself and maybe explain to me where I am going wrong I can provide you the complete source code. I thank you very much for all the help.

**Comment by etingof** [comment]
It feels like the problem is that you are sending your SNMP agent an OID which addresses a table column but OID's tail part (which is beyond the columnar OID) is too short to fill up all the indices of that table. Specifically, it fails at the table index which has `Integer32` type.

So I think you should look at the request OID that causes this exception and make sure its trailing part is long enough to populate all the indices specified by that SNMP table.

You can read a bit more on the background of SNMP tables and indices [here](http://snmplabs.com/pysnmp/docs/pysnmp-hlapi-tutorial.html#working-with-snmp-tables) for example.

**Comment by etingof** [comment]
Feel free to re-open this issue if it's not resolved. Thanks! ;)
