### ISSUE TITLE
Need Help with the steps in making simple  SNMP get request

### ISSUE THREAD

**Issue by Breme** [etingof/pysnmp#136]
Hi,
I'm new to SNMP, I want to do a simple SNMP get command to a EDVA device, please let me know where I went wrong,

```
from pysnmp.hlapi import *

errorIndication, errorStatus, errorIndex, varBinds = next(
    getCmd(SnmpEngine(),
           CommunityData('public', mpModel=1),
           UdpTransportTarget(('myip', 161)),
           ContextData(),
           ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysDescr', 0)))
)

if errorIndication:
    print(errorIndication)
elif errorStatus:
    print('%s at %s' % (errorStatus.prettyPrint(),
                        errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
else:
    for varBind in varBinds:
        print(' = '.join([x.prettyPrint() for x in varBind]))
```

If I execute this I'm getting "No SNMP response received before timeout" as output
It seems to be a error in the snmp Engine itself, should I configure something else?

Also don't get what exactly is a MIB, should I load it before executing the above code?

**Comment by Breme** [comment]
Hi ,
Thanks for the reply. I tried the default code as mentioned by you above, and got "Bad IPv4/UDP transport address demo.snmplabs.com@161: [Errno 11002] getaddrinfo failed" error.

the whole error message is,
Traceback (most recent call last):
  File "C:\Users\breme_b\AppData\Local\Programs\Python\Python36\lib\site-packages\pysnmp\hlapi\asyncore\transport.py", line 60, in _resolveAddr
    socket.IPPROTO_UDP)[0][4][:2]
  File "C:\Users\breme_b\AppData\Local\Programs\Python\Python36\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\breme_b\Desktop\pythonbasics\public.py", line 6, in <module>
    UdpTransportTarget(('demo.snmplabs.com', 161)),
  File "C:\Users\breme_b\AppData\Local\Programs\Python\Python36\lib\site-packages\pysnmp\hlapi\transport.py", line 19, in __init__
    self.transportAddr = self._resolveAddr(transportAddr)
  File "C:\Users\breme_b\AppData\Local\Programs\Python\Python36\lib\site-packages\pysnmp\hlapi\asyncore\transport.py", line 63, in _resolveAddr
    '@'.join([str(x) for x in transportAddr]), sys.exc_info()[1]))
pysnmp.error.PySnmpError: Bad IPv4/UDP transport address demo.snmplabs.com@161: [Errno 11002] getaddrinfo failed
Thanks ,
Breme

**Comment by etingof** [comment]
> demo.snmplabs.com@161: [Errno 11002] getaddrinfo failed

This looks like either DNS or network connectivity problem with the machine you run this script on. It has nothing to do with pysnmp.

**Comment by Breme** [comment]
Thanks a lot, it is working from our Lab network. As you mentioned it is a firewall issue
