### ISSUE TITLE
Resolve Named Value to Variable

### ISSUE THREAD

**Issue by devlarosa** [etingof/pysnmp#140]
I have this MIB definition

```
BasicState ::= TEXTUAL-CONVENTION
    STATUS      current
    DESCRIPTION "A description"
    SYNTAX      INTEGER
                {
                    state1 (1),
                    state2 (2),
		    state3 (3)
                }
```
which generates this code with mibdump.py

```
class BasicState(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + SingleValueConstraint(1, 2, 3)
    namedValues = NamedValues(("state1", 1), ("state2", 2), ("state3", 3))
```
Is there a way to resolve a value (e.g. 'state1') to a Integer32 variable?
thanks in advance!

**Comment by etingof** [comment]
With fresh pysnmp/pyasn1 `str()` on the object should return `state1` while `int()` should give you `1` integer. 

Is this what you are asking about? ;-)

**Comment by devlarosa** [comment]
What I want to do is pass a typed value to a setCmd.
Now I'm passing a Integer32(1), but I wish I could transform state1 to that value, if you know what i mean ... :)
```
        errorIndication, errorStatus, errorIndex, varBinds = next(
            setCmd(SnmpEngine(),
                   CommunityData(self.commmunity, mpModel=1),
                   UdpTransportTarget((self.host, self.port)),
                   ContextData(),
                   ObjectType(ObjectIdentity(oid), Integer32(1)),
                   lookupMib=False, lexicographicMode=False)
        )
```

**Comment by etingof** [comment]
You should refer to the MIB object then:

    ObjectType(ObjectIdentity('YOUR-MIB', 'yourMibObject', 0), 'state1'),

That way `ObjectIdentity` will pull the `BasicState` class out of `YOUR-MIB.py` and instantiate it with the `state1` literal.

**Comment by devlarosa** [comment]
That's it!
thanks a lot
