### ISSUE TITLE
PySNMP with PEX

### ISSUE THREAD

**Issue by lucklucif** [etingof/pysnmp#141]
Hello,

I have an error when i try to create a PEX (https://github.com/pantsbuild/pex) for my script:
`pysnmp.smi.error.MibNotFoundError: No module __SNMP-FRAMEWORK-MIB loaded at <pysnmp.smi.builder.MibBuilder object at 0x7f55ecd54748>`

Even after i tried in my code to load modules:
`    mibBuilder = builder.MibBuilder()
    compiler.addMibCompiler(mibBuilder, sources=['/tmp/mibs'])
    mibBuilder.addMibSources(builder.DirMibSource('/tmp/mibs'))

    mibBuilder.loadModules(
        'SNMPv2-MIB', 'SNMP-FRAMEWORK-MIB', 'SNMP-COMMUNITY-MIB'
    )`

**Comment by etingof** [comment]
These `*-MIB.py` files are never imported explicitly, rather then are dynamically loaded by the running code. This may have the effect of the statically analysing tool not seeing them as belonging to the project. Thus just omitting these files altogether.

In old times, when py2exe was young and kicking, you could [tell it explicitly](http://snmplabs.com/pysnmp/faq/py2exe-throws-error.html) that you need these files. I suppose PEX should have something similar.

**Comment by lucklucif** [comment]
Yes i found the issue in PEX. Thanks
