### ISSUE TITLE
Getting valid values from MIB

### ISSUE THREAD

**Issue by devlarosa** [etingof/pysnmp#144]
Is there a way to obtain the valid values of a certain scalar?
For instance, I've got this code in a Python MIB module MYMODULE :

```
class SomeStatus(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + SingleValueConstraint(1, 2, 3)
    namedValues = NamedValues(("initializing", 1), ("running", 2), ("exiting", 3))

[...]

myStatus = MibScalar((1, 3, 6, 1, 4, 1, 8173, 1, 1, 1, 1, 1, 5), SomeStatus()).setMaxAccess("readwrite")
```
Then, in the manager I create an ObjectType like this:

ObjectType(ObjectIdentity(['MYMODULE', 'myStatus', '0']), **value**).resolveWithMib(__mibView)

I want to get those NamedValues: initializing, running, exiting

Thanks in advance

**Comment by etingof** [comment]
Well, `SomeStatus.namedValues` should give you a [dict like object](http://snmplabs.com/pyasn1/pyasn1/type/namedval/namedval.html) holding the name-value mapping.

**Comment by devlarosa** [comment]
i've come to the conclusion this morning, that’s why i closed the issue :)

Thanks anyway
