### ISSUE TITLE
Bug in RFC1158-MIB.py, leading to "NameError: name 'snmpInReadOnlys' is not defined"

### ISSUE THREAD

**Issue by svenpanne** [etingof/pysnmp#146]
In pysnmp 4.4.4, there seems to be a bug in RFC1158-MIB.py: https://github.com/etingof/pysnmp/blob/4d57bdbbfe08d387ac844824075c2ebc366b88a8/pysnmp/smi/mibs/RFC1158-MIB.py#L19-L20

In the second line, `snmpInReadOnlys` should probably be `snmpOutReadOnlys`, otherwise one gets a `NameError` quite easily:

```python
from pysnmp.smi.builder import MibBuilder
b = MibBuilder()
b.loadTexts = True
b.loadModules()
```
results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/omd/sites/heute/lib/python/pysnmp/smi/builder.py", line 368, in loadModules
    self.loadModule(modName, **userCtx)
  File "/omd/sites/heute/lib/python/pysnmp/smi/builder.py", line 336, in loadModule
    'MIB module \"%s\" load error: %s' % (modPath, traceback.format_exception(*sys.exc_info()))
pysnmp.smi.error.MibLoadError: MIB module "/omd/sites/heute/lib/python/pysnmp/smi/mibs/RFC1158-MIB.pyc" load error: ['Traceback (most recent call last):\n', '  File "/omd/sites/heute/lib/python/pysnmp/smi/builder.py", line 331, in loadModule\n    exec (modData, g)\n', '  File "/lib/python/pysnmp/smi/mibs/RFC1158-MIB.py", line 20, in <module>\n', "NameError: name 'snmpInReadOnlys' is not defined\n"]
```

I have no clue how RFC1158-MIB.py is generated, it could as well be a bug in pysmi...

**Comment by etingof** [comment]
Fixed in 4b21d3da293c7adc84f5f7b634bb4256397b3e84. 

I so not think this is a pysmi problem -- this file may be modified manually, that's why it's shipped along with pysnmp.

Thanks for the heads up!
