### ISSUE TITLE
Filtering not working?

### ISSUE THREAD

**Issue by sargon** [etingof/pysnmp#16]
Hi according to documentation following should be equivalent with the appended snmpwalk:

    from pysnmp.hlapi import *
  
    for (errorIndication,
         errorStatus,
         errorIndex,
         varBinds) in nextCmd(SnmpEngine(),
                              UsmUserData('usr-md5-none', 'authkey1'),
                              UdpTransportTarget(('demo.snmplabs.com', 161)),
                              ContextData(),
                              ObjectType(ObjectIdentity('IF-MIB'))):
    
        if errorIndication:
            print(errorIndication)
            break
        elif errorStatus:
            print('%s at %s' % (errorStatus.prettyPrint(),
                                errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
            break
        else:
            for varBind in varBinds:
                print(' = '.join([x.prettyPrint() for x in varBind]))

> snmpwalk -v3 -lauthPriv -u usr-md5-none -A authkey1 -X privkey1 demo.snmplabs.com IF-MIB::

I am doing this for the according SNMP-v2 code and I get following difference in output:
> sargon@....:~/workspace/private/pysnmp$ snmpwalk -v2c -c .... -m ALL .... IFMIB | wc -l
> 628

> python3 test.py | wc
> 48083

For some reason that is more than data than expected, to be explicit that is the damn whole snmpwalk without reduction.

**Comment by etingof** [comment]
If you want pysnmp to stop walking the agent once the "next" OID does not belong to the OID subtree defined in specific MIB, try adding `lexicographicMode=False` to `nextCmd()` like shown in [this example](http://pysnmp.sourceforge.net/examples/hlapi/asyncore/sync/manager/cmdgen/table-operations.html#fetch-whole-snmp-table).
