### ISSUE TITLE
The way exceptions are caught/handled/re raised in AsyncoreDispatcher.runDispatcher()

### ISSUE THREAD

**Issue by SimenZhor** [etingof/pysnmp#167]
In the file: `pysnmp/pysnmp/carrier/asyncore/dispatch.py` (I suppose `pysnmp/pysnmp/carrier/asyncio/dispatch.py` and `pysnmp/pysnmp/carrier/twisted/dispatch.py` as well)
All exceptions thrown in the callback-function will be caught and re-raised as a PySnmpError, preventing the user to throw their own exceptions within the callback function.

I'm no Python expert, but from my perspective it seems like this could be replaced by a simple `raise` instead of `raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))`. I obviously don't know what this is intended to catch though, so please only consider it a suggestion.

The try/except block I'm talking about:
```Python
    def runDispatcher(self, timeout=0.0):
        while self.jobsArePending() or self.transportsAreWorking():
            try:
                loop(timeout and timeout or self.timeout,
                     use_poll=True, map=self.__sockMap, count=1)
            except KeyboardInterrupt:
                raise
            except:
                raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
            self.handleTimerTick(time())
```

**Comment by etingof** [comment]
Would [this change](https://github.com/etingof/pysnmp/pull/168) help? The better alternative would be chained exceptions, though those are not available in Python 2.

**Comment by SimenZhor** [comment]
I suppose the `self.cause` attribute does help a lot, but I don't think it's very intuitive for the average programmer that their exception isn't caught because they have to catch it as another exception and then check it's `cause` attribute. So if this is the approach you're going with I think this needs a decent example and some good documentation.

By the way, the code you proposed wasn't python 2.7 compliant, I at least had to modify it to pass `self` and cast `self.cause[1]` to string in order to concatenate it with the string message. I did it like this:

`Exception.__init__(self, message + ', caused by \'' + str(self.cause[1]) + '\'\n An error of type: ' + str(self.cause[0])) + ' wrapped inside a \'PySnmpError\''`

As you can see, I also attempted to add a hint in the error message that the whatever error isn't being caught as it's supposed to is disguised as a PySnmpError.

**Comment by etingof** [comment]
The issue you've raised (thank you!) is not that obvious how to resolve...

The trade off I can see is this: if we leak user (and thus pretty much all) exceptions up to the caller, then when pysnmp wants to communicate its own errors upwards it will need to piggyback user exceptions which looks quite fragile because the structure of user exception object can be anything.

The other way round when user exceptions are piggybacked on pysnmp exception objects seems more reliable and predictable, though not that convenient and obvious to the user. This is what #168 is trying to implement.

The best way would probably be to use [PEP3134](https://www.python.org/dev/peps/pep-3134/), but that does not work with aged Pythons...

**Comment by SimenZhor** [comment]
I don't know exactly which exceptions you are expecting to see during callback, but wouldn't the best practice here be to raise the exceptions (`PySnmpError`) from a level below what's currently being done? 
I'm already on deep water here, and probably won't have much more to contribute to the solution of this issue, but the way I see it, this exception should be thrown within the classes that are represented inside the callback function (`SnmpEnigne()` and all it's custom class attributes). Instead of being thrown, caught, renamed and thrown again. As long as you guys have control on your own exceptions whatever mistakes the user makes should be his/hers to catch and fix in my opinion.

I appreciate the effort you put in here by the way! I'm just attempting to contribute as much as possible, although it's a bit hard when I don't know exactly what this piece of code is here to prevent :) Unless anything I've said is unclear and you are happy with your solution, feel free to close this issue. You have way more knowledge of the sorrounding environment to these functions than I do.

**Comment by etingof** [comment]
> By the way, the code you proposed wasn't python 2.7 compliant, I at least had to modify it to pass self and cast self.cause[1] to string in order to concatenate it with the string message. 

Oh, indeed! That is fixed.

**Comment by etingof** [comment]
> As long as you guys have control on your own exceptions whatever mistakes the user makes should be his/hers to catch and fix in my opinion.

You are right, the reason why main loop is so aggressive wrt catching everything is that pysnmp itself calls many libraries which may raise many different exceptions. For example: `socket.error` can be raised. If pysnmp is used within a large application, this `socket.error` exception would be hard to interpret - is it SNMP problem or some other I/O...? Other than that, existing apps may expect just `PySnmpError` to bubble up, not other exceptions.

You may argue that pysnmp should be guarding its calls to the underlaying libraries and raise `PySnmpError` from there. I agree, trouble is that it immediately introduces a big change in behavior as not all exceptions is realistic to catch before they show up in bug reports...

So may be this PR improves the situation, but the real solution would be to go through the code and guard all calls to the external libs.

**Comment by etingof** [comment]
Alright, I have to merge this now to get this partial improvement landing in the upcoming release.
