### ISSUE TITLE
Not getting any output using snmpwalk.py but return output with snmpwalk command

### ISSUE THREAD

**Issue by bmangesh** [etingof/pysnmp#174]
Hi,
I am not getting any output using below command:

```
snmpwalk.py   -v 3 -u user1 -l noAuthNoPriv 172.16.2.94 sysName.0
```

but if i use same argument with snmpwalk command it works.
snmpwalk output:

```
[root@elk-stack SNMPpython]# snmpwalk   -v 3 -u user1 -l noAuthNoPriv 172.16.2.94 sysName.0
SNMPv2-MIB::sysName.0 = STRING: ldap.in.example.com.
```

**Comment by etingof** [comment]
tl;dr; Try 

```
snmpwalk.py   -v 3 -u user1 -l noAuthNoPriv 172.16.2.94 sysName
```

The thing is that `snmpwalk` first tries to query the exact object you give it (with SNMP GET command), then goes on with the GETNEXT iterations.

The `snmpwalk.py` tool does not do `GET` so it goes straight to GETNEXT which probably returns the "next" object which immediately goes out of scope so the output is empty.

Consider:

```
$ snmpwalk.py -v2c -c public demo.snmplabs.com SNMPv2-MIB::sysDescr.0
$ snmpwalk.py -v2c -c public demo.snmplabs.com SNMPv2-MIB::sysDescr
SNMPv2-MIB::sysDescr.0 = DisplayString: Linux zeus 4.8.6.5-smp #2 SMP Sun Nov 13 14:58:11 CDT 2016 i686 
```

**Comment by bmangesh** [comment]
Thanks, it's working with the solution you provided.
