### ISSUE TITLE
twisted: errors that are old-style classes do not work with Failure in callbacks

### ISSUE THREAD

**Issue by cjrh** [etingof/pysnmp#18]
Hi!
- Python 2.7.12
- pysnmp (4.3.2)
- Twisted (16.4.1)

First, Thanks for all your excellent work on pySNMP 👍 

There seems to be a problem with running pySNMP with Twisted with respect to catching exceptions.  

On this line `pysnmp/hlapi/twisted/cmdgen.py:468`, the code looks like this:

```
    def __cbFun(snmpEngine, sendRequestHandle,
                errorIndication, errorStatus, errorIndex,
                varBindTable, cbCtx):
        lookupMib, deferred = cbCtx
        if errorIndication:
            deferred.errback(Failure(errorIndication))   # <<===  Here
        else:
            deferred.callback(
                (errorStatus, errorIndex,
                 [vbProcessor.unmakeVarBinds(snmpEngine, varBindTableRow, lookupMib) for varBindTableRow in varBindTable])
            )
```

At the section marked, imagine that the `errorIndication` is a `requestTimedOut` error.  If we now jump to `pysnmp/proto/errind.py:70`, we see where that object is defined:

```
class RequestTimedOut(ErrorIndication):
    pass

requestTimedOut = RequestTimedOut('No SNMP response received before timeout')
```

The `RequestTimedOut` class inherits from `ErrorIndication` which is created at the top of `errind.py`:

```
class ErrorIndication:
    """SNMPv3 error-indication values"""
    def __init__(self, descr=None):
        self.__value = self.__descr = self.__class__.__name__[0].lower() + self.__class__.__name__[1:]
        if descr:
            self.__descr = descr

    <snip>
```

So `ErrorIndication` is an old-style class.  The problem with this is that the twisted errback system won't work with old-style classes.  In my outer error handlers, the `Failure` value is given as a `TypeError`, not `RequestTimedOut`:

```
exceptions.TypeError: exceptions must be classes, or instances, not type
```

I have experimented with monkeypatching `errind.py` using this code in my main module:

```
# Monkeypatch pysnmp
import pysnmp.proto.errind as errind

class RequestTimedOut(Exception):
    pass

errind.RequestTimedOut = RequestTimedOut
errind.requestTimedOut = RequestTimedOut(
    'No SNMP response received before timeout'
)

<main function follows>
```

This appears to resolve the problem, and I am able to catch `RequestTimedOut` as a normal exception in my calling code.

The twisted documentation for the `Failure` class is linked here:

https://twistedmatrix.com/documents/current/api/twisted.python.failure.Failure.html#__init__

It mentions that it wants an `Exception` instance (or descendant we presume) to be passed to the `Failure` constructor, which is of course not what is currently being passed.

My proposal would be to make the `ErrorIndication` class (in `errind.py`) a new-style class by inheriting from `Exception`, but I am completely new to the pysnmp code base, and I don't know what that would break.

It is possible that I have missed some important detail, and if so, I apologise for wasting your time! Thanks again for all your work on pySNMP!

**Comment by etingof** [comment]
Thank you for your report!

Is it a new-style class that is required by Twisted or errback needs `Exception` instance? Current pysnmp master has all classes reworked into new-style ones. Does that fix the issue you experience?

If not, would it help to make pysnmp passing `Exception(errorIndication)` to Twisted errback?

I'm a bit reluctant to base `ErrorIndication` on `Exception` because errorIndication is not necessarily raised, sometimes it is dealt with as just a container object.

**Comment by cjrh** [comment]
Thanks for looking into this.

It's great to hear about the changes in master.  I did not check that yet.  You also make a good point about "new style"  vs "Exception" instances.  Re-reading the twisted docs, it sounds like `Failure` really does want to wrap an exception instance, not just any old object.  

But, let me first try it on trunk and see what happens 👍

**Comment by cjrh** [comment]
I have upgraded to the new version (4.3.3).  I see that the error objects in pysnmp now are based on new-style classes, but alas, I think twisted wants raised things to be actual exceptions (i.e., ultimately inherited from `Exception`) in order to wrap them in `Failure` instances.  I regret referring to "old-style classes" in my initial description of the issue, as I think that was misleading of me and I apologise :)

Therefore, in my code I am still monkey-patching the pysnmp error classes to inherit from `Exception`.  If I get a chance, I'll try to make a working example to demonstrate the issue.  I should have done this right from the start.

**Comment by etingof** [comment]
No worries, migration to new-style classes and general code update is a good thing anyway! ;-)

May be we could intercept the non-Exception based exceptions at the pysnmp's Twisted adaptation code and re-raise them wrapped properly? 

I reproducer would be very handy, if you could come up with one! ;-)

Thank you!
