### ISSUE TITLE
LICENSE.rst missing from sdist uploaded on PyPI

### ISSUE THREAD

**Issue by nehaljwani** [etingof/pysnmp#184]
https://pypi.io/packages/source/p/pysnmp/pysnmp-4.4.5.tar.gz

**Comment by etingof** [comment]
The missing license has been recovered in commit 34836cc48453abcc3f9724b26a798b903f40e31b.

BTW, it is still in place in the wheel package. ;-)

Thanks!

**Comment by etingof** [comment]
jfyi: pysnmp 4.4.6 with this fix has been released
