### ISSUE TITLE
Error creating Bits subtype with named values

### ISSUE THREAD

**Issue by inguin** [etingof/pysnmp#189]
After upgrading to pysnmp 4.4.5 the following construct (created by libsmi2pysnmp) no longer works:

```python
from pysnmp.proto.rfc1902 import Bits
from pyasn1.type.namedval import NamedValues
Bits().subtype(namedValues = NamedValues())
```

The backtrace is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pysnmp/proto/rfc1902.py", line 205, in subtype
    return univ.OctetString.subtype(self, *args, **kwargs).setFixedLength(self.getFixedLength())
  File "/usr/lib/python3.6/site-packages/pyasn1/type/univ.py", line 913, in subtype
    return base.AbstractSimpleAsn1Item.subtype(self, value, **kwargs)
  File "/usr/lib/python3.6/site-packages/pyasn1/type/base.py", line 361, in subtype
    initializers[arg] += option
KeyError: 'namedValues'
```

**Comment by inguin** [comment]
Thanks for the hint! Unfortunately my Linux distribution (Fedora) does not seem to include `pysmi`. We're using `pysnmp` for automatic CI tests on our build system, and I'd like to keep the dependencies to a bare minimum.

`libsmi2pysnmp` is very convenient, so I'd like to keep on using it if possible. I'll gladly adapt it to work with newer `pysnmp` versions, though.

**Comment by inguin** [comment]
The MIB is part of the embedded system that is being tested with the help of `pysnmp`. It's essential that the Python module is always compiled from the latest checked in version.

I tried to use the `mibdump.py` output instead of the file generated by `libsmi2pysnmp`, but I'm getting `pyasn1.error.PyAsn1Error: Duplicate name ...` errors. That might be a usage error in our test scripts, though.

**Comment by etingof** [comment]
So what's the full traceback and what's the MIB you are trying to compile?

**Comment by inguin** [comment]
The MIB in question can be downloaded at: http://cdn.raritan.com/download/px3/version-3.4.0/PDU2_MIB_3.4.0_44367.txt. It certainly has its peculiarities, but to my best knowledge it's compliant with all standards.

I'm getting the following error when trying to access one of the bitfield values (like `outletDeviceCapabilities.1.1`):

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pysnmp/smi/rfc1902.py", line 867, in resolveWithMib
    self.__args[1] = self.__args[0].getMibNode().getSyntax().clone(self.__args[1])
  File "/usr/lib/python3.6/site-packages/pysnmp/proto/rfc1902.py", line 202, in clone
    return univ.OctetString.clone(self, *args, **kwargs).setFixedLength(self.getFixedLength())
  File "/usr/lib/python3.6/site-packages/pyasn1/type/univ.py", line 869, in clone
    return base.AbstractSimpleAsn1Item.clone(self, value, **kwargs)
  File "/usr/lib/python3.6/site-packages/pyasn1/type/base.py", line 311, in clone
    return self.__class__(value, **initilaizers)
  File "/usr/lib/python3.6/site-packages/pysnmp/proto/rfc1902.py", line 603, in __new__
    Bits = cls.withNamedBits(**kwargs.pop('namedValues'))
  File "/usr/lib/python3.6/site-packages/pysnmp/proto/rfc1902.py", line 642, in withNamedBits
    class X(cls):
  File "/usr/lib/python3.6/site-packages/pysnmp/proto/rfc1902.py", line 643, in X
    namedValues = cls.namedValues + namedval.NamedValues(*values.items())
  File "/usr/lib/python3.6/site-packages/pyasn1/type/namedval.py", line 156, in __add__
    return self.__class__(*tuple(self.items()) + tuple(namedValues.items()))
  File "/usr/lib/python3.6/site-packages/pyasn1/type/namedval.py", line 66, in __init__
    raise error.PyAsn1Error('Duplicate name %s' % (name,))
pyasn1.error.PyAsn1Error: Duplicate name rmsCurrent
```

**Comment by etingof** [comment]
I ponder reproducing this issue, but not quite successfully so far. Here's my reproducer that does not fail:

```
from pysnmp.smi import builder, view, rfc1902, error

mibBuilder = builder.MibBuilder()
mibView = view.MibViewController(mibBuilder)

mibVar = rfc1902.ObjectType(rfc1902.ObjectIdentity('PDU2-MIB', 'outletDeviceCapabilities', 1, 1), ("rmsCurrent", "peakCurrent"))

mibVar.resolveWithMib(mibView)

print(tuple(mibVar[0]), repr(mibVar[1]))
```

How do you cause it to fail?

**Comment by inguin** [comment]
That script triggers the issue here. Here's exactly what I did:

- Started with a Fedora 28 system, no pysnmp packages installed
- Get pysnmp and pysmi from PyPI: `pip3 install --user pysnmp`
- Clone `etingof/pysnmp` for the `mibdump.py` utility
- Download the MIB from the link above
- Run `python3 mibdump.py PDU2-MIB`
- Run `python3 pysnmp-test.py`

**Comment by etingof** [comment]
Could you share the `pysnmp-test.py` script so I could reproduce those steps please?

BTW, you could `pip install pysmi` and get `mibdump.py` that way.

**Comment by etingof** [comment]
> What I see is that in the NamedValues concatenation (proto/rfc1902.py:643) both sides contain the list of bit definitions from the MIB; hence the duplicate name error.

Yes, that's what I thought might be the problem. I just wanted to have it failing clearly before fixing it.

I will it out with my reproducer.

Have a safe trip! ;-)

**Comment by inva-raritan** [comment]
Back from vacation. Quick update:

1. My initial problem can be resolved by changing `libsmi2pysnmp` to emit `Bits().clone(namedValues = ...)` instead of `Bits().subtype(namedValues = ...)`, as does `mibdump.py`.
2. The duplicate name exceptions are gone after applying 74434d71 on top of 4.4.5.

That's good enough for me. I'm not sure if the `Bits().subtype()` syntax is still supposed to work; if it's unsupported this issue can be closed. Thanks!

**Comment by etingof** [comment]
>  I'm not sure if the Bits().subtype() syntax is still supposed to work; if it's unsupported this issue can be closed. 

Conceptually, `.subtype()` better represents what's going on from data modelling perspective. I think it should work with once 74434d7 is in place.

**Comment by etingof** [comment]
jfyi: pysnmp 4.4.6 with this fix has been released
