### ISSUE TITLE
Is pip package broken ?

### ISSUE THREAD

**Issue by andreimircescu** [etingof/pysnmp#197]
if you install the 4.4.6 version from pip, you can see that hlapi.v3arch module does not exist. The python module structure is changed.

If you look on github releases, with the same version, it has hlapi.v3arch.

Is this desired ?

**Comment by etingof** [comment]
The version I just pulled from pip seems to have `pysnmp.hlapi` subpackage in place:

```
$ python3 -m venv venv3
$ . venv3/bin/activate
(venv3) $ pip install pysnmp
Collecting pysnmp
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/99/1a/9e0cdf6a963998185eeebc2a3fa368aa448cac73126a98a4cbf7bdfe85c7/pysnmp-4.4.6-py2.py3-none-any.whl (291kB)
    100% |████████████████████████████████| 296kB 177kB/s 
Collecting pysmi (from pysnmp)
  Using cached https://files.pythonhosted.org/packages/74/d6/92bf7c9f16d365a17e26a97e2340d194b62e46c7d27effa71682c081a17d/pysmi-0.3.1-py2.py3-none-any.whl
Collecting pycryptodomex (from pysnmp)
  Downloading https://files.pythonhosted.org/packages/d7/12/c45b6e7506b39bfd8ca661d9bf8cbd6ac9d20e9bb9108dfffcd11f202b46/pycryptodomex-3.6.6-cp35-cp35m-manylinux1_x86_64.whl (7.4MB)
    100% |████████████████████████████████| 7.4MB 105kB/s 
Collecting pyasn1>=0.2.3 (from pysnmp)
  Using cached https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl
Collecting ply (from pysmi->pysnmp)
  Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Installing collected packages: ply, pysmi, pycryptodomex, pyasn1, pysnmp
Successfully installed ply-3.11 pyasn1-0.4.4 pycryptodomex-3.6.6 pysmi-0.3.1 pysnmp-4.4.6
$ python -c 'import pysnmp.hlapi'
$
$ ls venv3/lib/python3.5/site-packages/pysnmp/hlapi/
asyncio  asyncore  auth.py  context.py  __init__.py  lcd.py  __pycache__  transport.py  twisted  varbinds.py
$ grep __version__  venv3/lib/python3.5/site-packages/pysnmp/__init__.py 
__version__ = '4.4.6'
```

Could you please elaborate how could I reproduce the effect you experience?

The master branch at GitHub holds yet unreleased `pysnmp 5` which has slightly different (though compatible) package layout. Could it be that you use GitHub master?

**Comment by andreimircescu** [comment]
if you do
 wget https://github.com/etingof/pysnmp/archive/v4.4.6.tar.gz
(directly from github releases)
tar -xvf  ...

I see a different folder structure:
__init__.py  transport.py  v1arch  v3arch  varbinds.py

**Comment by etingof** [comment]
Ah, so it's GitHub release that is broken, not PyPI one?

I've just re-released [4.4.6](https://github.com/etingof/pysnmp/releases/tag/v4.4.6) on GitHub.  Please poke me if you find anything else.

The changed package structure is due to accidental release of pysnmp 5.

**Comment by andreimircescu** [comment]
yes, actually I didn't know which one was broken,  one must be :)

**Comment by etingof** [comment]
I hope it's alright now. Thank you! ;-)
