### ISSUE TITLE
Can you please add some example code of receving snmp V3 Traps and Notifications

### ISSUE THREAD

**Issue by zhaohangbo** [etingof/pysnmp#2]
Can you please add some example code of receving snmp V3 Traps and Notifications

**Comment by etingof** [comment]
How about [these examples](http://snmplabs.com/pysnmp/examples/v3arch/asyncore/contents.html#notification-receiver-applications)?

**Comment by zhaohangbo** [comment]
Thanks lot. It's useful. 
And how can the manager deal with the received OIDs usually ? (how to interpret the OIDs) 
And how can I store the received data into ElasticSearch or forward to Kafka ?

**Comment by etingof** [comment]
In pysnmp, OID acts like a tuple of integer sub-OIDs. Or as a human-friendly string of dot-separated integers. So manager can use either of these two representations.

Take a look at how people [deal](http://stackoverflow.com/questions/35017996/need-to-get-mac-address-tables-from-d-link-switches-with-python) with pysnmp and MongoDB for inspiration. ;)

**Comment by ReidLv** [comment]
> How about [these examples](http://pysnmp.sourceforge.net/examples/v3arch/asyncore/contents.html#notification-receiver-applications)?

Thanks etingof. 
The url connection has failed now, it connected to a new home page, can you please add the new one ? 0.0

**Comment by etingof** [comment]
Updated to point to [snmplabs.com](http://snmplabs.com/pysnmp/examples/v3arch/asyncore/contents.html#notification-receiver-applications). Keep in mind that these examples are also shipped with the code (in `examples`).

**Comment by Asalle** [comment]
@etingof it seems that snmplabs.com is down
