### ISSUE TITLE
The vlan information of two-layer swtich is incomplete

### ISSUE THREAD

**Issue by AAAwkake** [etingof/pysnmp#203]
Firstly,thank you for your pysnmp.There is a problem when I use pysnmp,I want to get the mac-table of the two-layer swtich,but i found that I can only get the information of vlan1,and there are 3 vlans of the swtich.
For example,there are vlan1,vlan11,vlan111 in the swtich,but I can only get the information of vlan1. It's normal for a three-layer switch.Hope you can response me:)

**Comment by AAAwkake** [comment]
now I can get the information of vtpVlanState of two-layer swtich .There are vlan1 vlan10 vlan30，but when I get mac-table,it only return me the information of vlan1 instead of all vlans

**Comment by linus-qintian** [comment]
Hello, I also encountered the same problem as you, did you find a suitable solution?
