### ISSUE TITLE
Agent Discovery

### ISSUE THREAD

**Issue by andreimircescu** [etingof/pysnmp#204]
is there support for snmpv3 discovery specified in RFC3414(https://tools.ietf.org/html/rfc3414#section-4) from the agent perspective. Basically, I want to respond to these requests. Are there any examples ?

**Comment by etingof** [comment]
When pysnmp is used in the command responder context (agent), it will handle SNMPv3 security parameters discovery automatically.

Is it that you are looking into somehow influencing this otherwise automatic and self-contained process?

**Comment by andreimircescu** [comment]
Found the issue, it was from my end. I will close this thread
