### ISSUE TITLE
change an OID value

### ISSUE THREAD

**Issue by andreimircescu** [etingof/pysnmp#208]
I'm using [this example](https://github.com/etingof/pysnmp/blob/master/examples/v3arch/asyncore/agent/cmdrsp/observe-request-processing.py) for the GET command:

I receive a notification for sysObjectID and it seems that my agent returns 1.3.6.1.4.1.20408:

```
Execution point: rfc3412.returnResponsePdu
* transportDomain: 1.3.6.1.6.1.1
* transportAddress: <ip>
* securityModel: 3
* securityName: usr-md5-des
* securityLevel: 3
* contextEngineId:
* contextName: 
* PDU: ResponsePDU:
 request-id=1889684380
 error-status=noError
 error-index=0
 variable-bindings=VarBindList:
  VarBind:
   name=1.3.6.1.2.1.1.2.0
   =_BindValue:
    value=ObjectSyntax:
     simple=SimpleSyntax:
      objectID-value=1.3.6.1.4.1.20408
```

My question, how can I change the value for sysObjectID ?

**Comment by andreimircescu** [comment]
I found another example but it seems is not complete:
http://snmplabs.com/pysnmp/faq/how-to-implement-agent-mib.html

**Comment by etingof** [comment]
It seems that you use the hooks tapping on SNMP engine's internal operations. Could you please explain what is your ultimate goal?

The OID being returned is taken from the MIB which is maintained by the SNMP engine. If your goal is to build SNMP agent serving certain OIDs, please check out [this](http://snmplabs.com/pysnmp/examples/v3arch/asyncore/agent/cmdrsp/agent-side-mib-implementations.html#implementing-scalar-mib-objects) or other examples.

**Comment by andreimircescu** [comment]
My ultimate goal is to have some custom implementation on generic OIDs and also support some custom OIDs

it's much better what you suggested, Initially I just hacked __SNMP-MIB but after, I created my own :)
