### ISSUE TITLE
LinkUp/Down traps does not work when you set a contextName 

### ISSUE THREAD

**Issue by andreimircescu** [etingof/pysnmp#216]
Given the following code:
```
from pysnmp.hlapi import *

errorIndication, errorStatus, errorIndex, varBinds = next(
    sendNotification(
        SnmpEngine(),
        UsmUserData('usr-sha-aes128', 'authkey1', 'privkey1',
                    authProtocol=usmHMACSHAAuthProtocol,
                    privProtocol=usmAesCfb128Protocol),
        UdpTransportTarget(('demo.snmplabs.com', 169)),
        ContextData(contextEngineId="testengine", contextName="testname"),
        'trap',
        NotificationType(
            ObjectIdentity('IF-MIB', 'linkUp'),
                           instanceIndex=(123,),
                           objects={('IF-MIB', 'ifIndex'): 123,
                                    ('IF-MIB', 'ifAdminStatus'): 'up',
                                    ('IF-MIB', 'ifOperStatus'): 'up'}
        )
    )
)

if errorIndication:
    print(errorIndication)
```

It will not send the packet but if we remove the contextName from contextData, the packet will be sent.

Cannot find any reason for this behavior

**Comment by etingof** [comment]
Ah, if you enable debugging:

```
from pysnmp import debug

debug.setLogger(debug.Debug('all'))
```

That would reveal the bug in pysnmp:

```
2018-11-02 18:19:58,037 pysnmp: StatusInformation: {'errorIndication': NoSuchContext('SNMP context now found',)}
```

It seems that `contextName` does not get through into SNMP configuration properly. Let me try to fix that....

**Comment by etingof** [comment]
> the interesting part is that other types of traps works with contextName. I tested with AuthFailure and it works.

The cause might be that `linkUp` implies including some interfaces table related objects, while `authenticationFailure` is just a solitary notification. Misconfigured VACM table for the non-default context name denies access to those interface OIDs effectively failing the entire PDU. :-(

**Comment by etingof** [comment]
PR #217 should have fixed this issue.

**Comment by andreimircescu** [comment]
tested it on 4.4.7 and the patch works.
