### ISSUE TITLE
Question: Get Source Address from response PDU in CBFUN SNMPv3

### ISSUE THREAD

**Issue by dapryor** [etingof/pysnmp#222]
I have been tasked  to do a large device discovery using python 2.7 and snmpv3.  I have completed the task using the asyncore portion of pysnmp, but have noticed that I have a few devices responding on the broadcast address of their subnet.  Since I am scanning a supernet of these subnets, I am unable to filter out the broadcast addresses.  Is there a way to access the PDUs source address inside of cbfun so perform a type of reverse path forwarding?  When I receive a "unknown usm user" error, I also want to check the source address.  

I see the the orignial PDU is masked to give parts of it to cbfun, but am unsure if there is a more simple way to access this info.

Any help would be appreiated.

**Comment by etingof** [comment]
You could [register a callback](https://github.com/etingof/pysnmp/blob/master/examples/v3arch/asyncore/manager/cmdgen/observe-request-processing.py#L34) which would be invoked before your application receives SNMP message. In the callback you will be given the peer address (`transportAddress`) which you could temporarily store and/or use for further processing.

**Comment by dapryor** [comment]
Thanks Ilya!  I am messing around to see if I can get the desired behavior.  Is there a list of execution points  with there descriptions?  I found 3 in the rfc3412.py file and can see the callback from rfc3412.sendPdu.  I am trying to find the correct exec point for a received message when I get the unknown usm user error.

**Comment by etingof** [comment]
Here is the list of those execution points:

- rfc2576.prepareDataElements:confirmed
- rfc2576.prepareDataElements:response
- rfc2576.prepareDataElements:sm-failure
- rfc2576.prepareDataElements:unconfirmed
- rfc2576.prepareOutgoingMessage
- rfc2576.prepareResponseMessage
- rfc2576.processIncomingMsg
- rfc2576.processIncomingMsg:writable
- rfc3412.prepareDataElements:confirmed
- rfc3412.prepareDataElements:internal
- rfc3412.prepareDataElements:response
- rfc3412.prepareDataElements:sm-failure
- rfc3412.prepareDataElements:unconfirmed
- rfc3412.prepareOutgoingMessage
- rfc3412.prepareResponseMessage
- rfc3412.receiveMessage:request
- rfc3412.receiveMessage:response
- rfc3412.returnResponsePdu
- rfc3412.sendPdu
- rfc3414.processIncomingMsg

You could grep them in the source or just register your callback with all of them to see when it hits the desired condition.

We could always add some more execution points whenever it makes sense.

**Comment by dapryor** [comment]
Hey Ilya.  rfc3412.prepareDataElements:internal is what I ended up using.  Sending to the broadcast address, I could see the IP that responded.  I will use this to filter out the broadcast addresses.

Thanks again.  You've been a great help.
