### ISSUE TITLE
Minor doc omission?

### ISSUE THREAD

**Issue by johnthagen** [etingof/pysnmp#25]
See: http://pysnmp.sourceforge.net/docs/pysnmp-hlapi-tutorial.html#specifying-mib-object

> The trailing zero is an indication of MIB object instance. Objects described in MIBs are just declarations, they never contain any data. Data is stored in MIB object instances that are addressed by **appending For** ...

Was there something missing here?

**Comment by etingof** [comment]
Hopefully fixed in 2ad5246
