### ISSUE TITLE
Q: is MIB required for GETNEXT command to operate?

### ISSUE THREAD

**Issue by fried-sausage** [etingof/pysnmp#252]
This is more of a question, as i am pretty knew to snmp protocol.
Given [this](http://snmplabs.com/pysnmp/examples/hlapi/asyncore/sync/manager/cmdgen/walking-operations.html) example from docs, is it possible that at some point SNMP agent will return oid which is unknown to pysnmp (not in default MIBs and not provided programmatically with .addMibSource and such)? Is such situation still possible with `lexicographicMode=True`? If yes, what happens?

**Comment by etingof** [comment]
It is indeed possible that the manager eventually receives an OID for which the manager does not have SMI info from a MIB. That won't change the way how GETNEXT command operates because SNMP always operates only on OIDs, not names of the MIB objects.

The latter only makes sense for humans because, given all this metadata in the MIBs, humans can make sense out of the (otherwise machine-friendly) management information.

**Comment by fried-sausage** [comment]
> manager eventually receives an OID for which the manager does not have SMI info from a MIB
Thanks. That also means manager won't be able to decode the value, as it's type is unknown. Is my understanding correct?

**Comment by etingof** [comment]
> That also means manager won't be able to decode the value, as it's type is unknown. Is my understanding correct?

No, the types of the values are embedded into ASN.1/DER encoding so SNMP parties can happily exchange OID-value pairs without any MIBs involved.

The only problem concerning the values is that if a MIB defines a value being so-called 'TEXTUAL-CONVENTION', the manager could only represent such value to a human reader in its base type form.

To give you an example: MAC and IP addresses are transferred as a sequence of octets. For the manager to turn these octets into the form we used to (e.g. DE:AD:BE:EF:00:00), a MIB would be necessary.

**Comment by fried-sausage** [comment]
I have one more question. How do i traverse the whole OID tree, including vendor specific OIDs (which, to my understanding, live under oid 1.3.6.1.4)? With this example, i only get oids starting with 1.3.6.1.2
```python
from pysnmp.hlapi import *

for (errorIndication,
     errorStatus,
     errorIndex,
     varBinds) in nextCmd(SnmpEngine(),
                          UsmUserData('usr-md5-none', 'authkey1'),
                          UdpTransportTarget(('demo.snmplabs.com', 161)),
                          ContextData(),
                          ObjectType(ObjectIdentity('1.3')),  # start from root
                          lexicographicMode=True):

    if errorIndication:
        print(errorIndication)
        break
    elif errorStatus:
        print('%s at %s' % (errorStatus.prettyPrint(),
                            errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
        break
    else:
        for varBind in varBinds:
            print(' = '.join([x.prettyPrint() for x in varBind]))


```

**Comment by etingof** [comment]
Just start at the higher (shorter) OID like `1.3.6` so you'd eventually hit `1.3.6.1.4`.

**Comment by fried-sausage** [comment]
Doesn't work for me. Should i create new issue?
