### ISSUE TITLE
MIB subtree already registered at MibScalar

### ISSUE THREAD

**Issue by LoveAries** [etingof/pysnmp#258]
This is my first time using pysnmp. I need to simulate agent, so I refer to some examples. But when I was running, I found an error.

I don't know much about SNMP. What's the reason for this mistake?

```
`File "pysnmp\smi\mibs\SNMPv2-SMI.py", line 432, in registerSubtrees
pysnmp.smi.error.SmiError: MIB subtree (1, 3, 6, 1, 6, 3, 10, 2, 1, 1, 0) already registered at MibScalar((1, 3, 6, 1, 6, 3, 10, 2, 1, 1), <SnmpEngineID value object at 0x397d0f0 tagSet <TagSet object at 0x37e35d0 tags 0:0:4> subtypeSpec <ConstraintsIntersection object at 0x39179d0 consts <ValueSizeConstraint object at 0x3842390 consts 0, 65535>, <ConstraintsUnion object at 0x3917a30 consts <ValueSizeConstraint object at 0x3917a10 consts 5, 32>>> encoding iso-8859-1 payload [0x80004fb8055748a990]>)caused by <class 'KeyError'>: 'state'
```
Here is the procedure I [refer to](https://stackoverflow.com/questions/41384941/using-pysnmp-to-write-an-snmp-agent-for-opennms), also [agent_test.txt](https://github.com/etingof/pysnmp/files/3062775/agent_test.txt).

**Comment by r0bc94** [comment]
Hello @LoveAries , 
as I'm running in the exact same issue, do you maybe remember what the solution to this issue was?
