### ISSUE TITLE
AsynccoreDispatcher catches SystemExit

### ISSUE THREAD

**Issue by cunkel** [etingof/pysnmp#259]
I have an application using pysnmp with a daemon that exits in response to SIGTERM by calling sys.exit from a signal handler.  I have seen unclean or failed exits from it due to pysnmp.carrier.asyncore.AsyncoreDispatcher.runDispatcher catching SystemExit.  The function includes specific handling for KeyboardInterrupt, but not for SystemExit,

I would suggest changing the bare except: to except Exception: and removing the special case for KeyboardInterrupt.

**Comment by cunkel** [comment]
Actually, it appears this change is already fixed in commit 588b9b902d19 ("Uppercase global constants (#238)").  I do have a minor cleanup in that the except KeyboardInterrupt is now redundant, for which I've submitted a separate PR.

**Comment by etingof** [comment]
Yes, I concur and this has been improved in master.
