### ISSUE TITLE
Not able to use pysnmp

### ISSUE THREAD

**Issue by rohitchormale** [etingof/pysnmp#267]
I am trying to run a script from examples but getting below errors -(examples/v1arch/asyncore/manager/ntfrcv/listen-on-ipv4-and-ipv6-interfaces.py)

```Traceback (most recent call last):
  File "listen-on-ipv4-and-ipv6-interfaces.py", line 23, in <module>
    from pysnmp.carrier.asyncore.dispatch import AsyncoreDispatcher
ImportError: No module named pysnmp.carrier.asyncore.dispatch
```

Interestingly on interpreter, I am able to import them. But during runtime only this problem appearing. 

**Environment**
Python 3.6.7
pysnmp==4.4.9

**Comment by etingof** [comment]
Perhaps pysnmp in not in your search path. Or may be you have multiple pythons on your system. 

May be try running your script with -v (python -v <script.py>) to see what modules it actually uses.

**Comment by rohitchormale** [comment]
I was running with sudo to acquire 162 port under virtual-environment. Seems like this is the [issue](https://askubuntu.com/a/245921/606480). Finally able to run by specifying absolute path to python interpreter. 
Thanks for help.
