### ISSUE TITLE
mpModel=1 but snmp version is 1

### ISSUE THREAD

**Issue by vitsumoc** [etingof/pysnmp#278]
Hello, thank you very much:
I am learning to manage my h3c switch using pysnmp, but I have a minor problem with the setCmd().

When I use the following code to try to modify a value of the switch, I find that pysnmp seems to treat my request as snmpv1.

Here is my code:
```
from pysnmp.hlapi.asyncore import *
from pysnmp import debug

debug.setLogger(debug.Debug('all'))

ftpServer = '192.168.1.129'
ftpuser = 'ftpuser'
ftppass = 'suyun2016'
hostAddress = '192.168.1.148'
hostPort = 161
community = 'public'
snmpEngine = SnmpEngine()
errorIndication, errorStatus, errorIndex, varBinds = next(
    setCmd(snmpEngine,
           CommunityData(community),
           UdpTransportTarget((hostAddress, hostPort)),
           ContextData(),
           ObjectType(ObjectIdentity('1.3.6.1.4.1.25506.2.4.1.2.4.1.2.1'),
                      Integer(1))))
```

This is the output of the debug:

```
2019-06-19 18:14:35,406 pysnmp: generateRequestMsg: Message:
 **version=1**
 community=public
 data=PDUs:
  set-request=SetRequestPDU:
   request-id=450553
   error-status=noError
   error-index=0
   variable-bindings=VarBindList:
    VarBind:
     name=1.3.6.1.4.1.25506.2.4.1.2.4.1.2.1
     =_BindValue:
      value=ObjectSyntax:
       simple=SimpleSyntax:
        integer-value=1
```
This makes me very confused, because another similar case of mine is correct.
Here is code:

```
from pysnmp.hlapi import *
hostAddress = '192.168.1.148'
hostPort = 161
community = 'public'
snmpEngine = SnmpEngine()
from pysnmp import debug
debug.setLogger(debug.Debug('all'))
errorIndication, errorStatus, errorIndex, varBinds = next(
    setCmd(snmpEngine,
           CommunityData(community),
           UdpTransportTarget((hostAddress, hostPort)),
           ContextData(),
           ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysName', 0),
                      'h1')))
```

The second piece of code can return a correct tuple, but the first piece of code will only return me an integer.

Can you please help me? thank you very much

**Comment by etingof** [comment]
Sorry for late response!

SNMP versions enumeration is weird - 0 stands for v1, 1 - for v2c and 3 - for v3. But not always, sometimes it's 2 that indicates v3. Depends on where you encounter it.

At any rate, your message is SNMP v2c.

I am not sure I understand your other question regarding the return value.

**Comment by lextm** [comment]
The value of 2 was once used by SNMP v2u, but v2u was later deprecated by v3,

https://github.com/lextudio/sharpsnmplib/blob/12.5.1/SharpSnmpLib/VersionCode.cs#L45

That's why there is a sudden jump from 1 (v2c) to 3 (v3).
