### ISSUE TITLE
"Ciphering services not available" error with SNMP V3 usage of pysnmp in python v3 virtual environment

### ISSUE THREAD

**Issue by ICKGeek** [etingof/pysnmp#285]
Hi Team,

I am trying to use pysnmp library with SNMP V3 settings with MD5 Auth protocol and AesCfb128 Priv protocol to obtain details from a switch. I am trying two things.

**1. Install pysnmp and all dependency packages (including pycrytpto) in base machine** 

**2. Create virtual environment for python3 and install pysnmp and all dependency packages (including pycrytpto) in this virtual environment.**

When I take the 1st approach,  details are retrieved properly. But when I try the 2nd approach, I am getting "Ciphering services not available" error. I checked that list of installed packages are pretty much same across the both.

**Here are the details of base machine**

```
$ pip3 list
pip (9.0.1)
ply (3.11)
pyasn1 (0.4.5)
pycryptodomex (3.8.2)
pysmi (0.3.4)
pysnmp (4.4.9)
setuptools (28.8.0)
```

**My Virtual Environment is created in location "/Users/<user_name>/Test/Python/Pysnmp"**

```
$ /Users/<user_name>/Test/Python/Pysnmp/bin/pip3 list

Package       Version
------------- -------
pip           18.1   
pipdeptree    0.13.2 
ply           3.11   
pyasn1        0.4.5  
pycryptodomex 3.8.2  
pysmi         0.3.4  
pysnmp        4.4.9  
setuptools    40.6.2 
```

**Here is the command that I am trying to use**

```
    for (errorIndication,errorStatus,errorIndex,varBinds) in nextCmd(SnmpEngine(),
        UsmUserData('test_user', 'test_password', 'test_password', usmHMACMD5AuthProtocol, usmAesCfb128Protocol),
        UdpTransportTarget((host, 161)), ContextData(),
        ObjectType(ObjectIdentity(oid)), lexicographicMode=False):
```

When I run this in base machine (like python3 script.py), it returns the details properly. 

But when I run it using the python installed inside virtual environment (like `/Users/<user_name>/Test/Python/Pysnmp/bin/python3 script.py)`, it returns as errorindication.

```
"**Ciphering services not available**"
```

What am I missing here?

Thanks

**Comment by ICKGeek** [comment]
I am not sure whether this is the good place to ask this question or whether I should ask it on stackoverflow. So I posted this on stackoverflow also @ https://stackoverflow.com/questions/57116952/ciphering-services-not-available-error-with-snmp-v3-usage-of-pysnmp-in-python

**Comment by etingof** [comment]
It feels like you have something wrong with your virtualenv. I'd factor out pysnmp here, try just this import:

```
python -c 'from Cryptodome.Cipher import AES'
```
(this is what pysnmp is doing). It should silently work out. If it does not, something is broken in your virtualenv. May be try to recreate it and reinstall everything...

**Comment by ICKGeek** [comment]
Thanks etingof for the reply.

I tried it out and it seems to have resolved the issue. For some reason virtualenv seem to have broken. Now, I tried it out again. This time, I am hitting "Segmentation fault". Below is the gdb call stack. Any suggestions on what could be going wrong? FYI, i have removed OCB files from the package as I do not want to use OCB encryption and needed to ship this to customers who includes military as well.

```
Program received signal SIGSEGV, Segmentation fault.  
0xf651dfb5 in AESNI_encrypt (bb=0x87f3ab8, in=0xf625f328 "", out=0x87af5e0 "", data_len=16) at src/AESNI.c:156
156     src/AESNI.c: No such file or directory.
        in src/AESNI.c
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.5-7.SCLC6_4.R3.0.2.i686 glibc-2.12-1.192.SCLC6_4.R3.0.1.i686 iveopenssl-1.0.2n-2.SCLC6_4.R3.0.2.i686 python36-libs-3.6
.2-2.SCLC6_4.R3.0.2.i686 xz-libs-4.999.9-0.3.beta.20091007git.SCLC6_4.R3.0.2.i686
(gdb) bt
#0  0xf651dfb5 in AESNI_encrypt (bb=0x87f3ab8, in=0xf625f328 "", out=0x87af5e0 "", data_len=16) at src/AESNI.c:156
#1  0xf69e4969 in CFB_start_operation (cipher=0x87f3ab8, iv=0xf625f328 "", iv_len=16, segment_len=16, pResult=0x879a4f4) at src/raw_cfb.c:97
#2  0xf690744f in ffi_call_SYSV () at src/x86/sysv.S:61
#3  0xf6907280 in ffi_call (cif=0xf6265188, fn=0xf69e4820 <CFB_start_operation>, rvalue=0xf62651e8, avalue=0xf62651d0) at src/x86/ffi.c:213
#4  0xf669adca in cdata_call (cd=0xf645f038, args=0xf644be3c, kwds=0x0) at c/_cffi_backend.c:3025
#5  0xf74d1a34 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#6  0xf74d2467 in _PyObject_FastCallKeywords () from /usr/lib/libpython3.6m.so.1.0
#7  0xf75966e1 in ?? () from /usr/lib/libpython3.6m.so.1.0
#8  0xf759c060 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#9  0xf7594f9c in PyEval_EvalFrameEx () from /usr/lib/libpython3.6m.so.1.0
#10 0xf759508c in ?? () from /usr/lib/libpython3.6m.so.1.0
#11 0xf7596461 in _PyFunction_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#12 0xf74d1b50 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#13 0xf74d260c in _PyObject_Call_Prepend () from /usr/lib/libpython3.6m.so.1.0
#14 0xf74e972a in ?? () from /usr/lib/libpython3.6m.so.1.0
#15 0xf74d26ba in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#16 0xf75389ce in ?? () from /usr/lib/libpython3.6m.so.1.0
#17 0xf7535744 in ?? () from /usr/lib/libpython3.6m.so.1.0
#18 0xf74d1a34 in _PyObject_FastCallDict () from /usr/lib/libpython3.6m.so.1.0
#19 0xf74d2467 in _PyObject_FastCallKeywords () from /usr/lib/libpython3.6m.so.1.0
#20 0xf75966e1 in ?? () from /usr/lib/libpython3.6m.so.1.0
#21 0xf759c060 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#22 0xf7594f9c in PyEval_EvalFrameEx () from /usr/lib/libpython3.6m.so.1.0
#23 0xf75960bc in ?? () from /usr/lib/libpython3.6m.so.1.0
#24 0xf759699f in PyEval_EvalCodeEx () from /usr/lib/libpython3.6m.so.1.0
#25 0xf750142c in ?? () from /usr/lib/libpython3.6m.so.1.0
#26 0xf74d26ba in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#27 0xf759bc84 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#28 0xf7594f9c in PyEval_EvalFrameEx () from /usr/lib/libpython3.6m.so.1.0
#29 0xf75960bc in ?? () from /usr/lib/libpython3.6m.so.1.0
#30 0xf759699f in PyEval_EvalCodeEx () from /usr/lib/libpython3.6m.so.1.0
#31 0xf750142c in ?? () from /usr/lib/libpython3.6m.so.1.0
#32 0xf74d26ba in PyObject_Call () from /usr/lib/libpython3.6m.so.1.0
#33 0xf759bc84 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.6m.so.1.0
#34 0xf7594f9c in PyEval_EvalFrameEx () from /usr/lib/libpython3.6m.so.1.0
#35 0xf75960bc in ?? () from /usr/lib/libpython3.6m.so.1.0
#36 0xf7596542 in ?? () from /usr/lib/libpython3.6m.so.1.0
#37 0xf7596752 in ?? () from /usr/lib/libpython3.6m.so.1.0
```

**Comment by etingof** [comment]
>  Any suggestions on what could be going wrong?

I think you should better bring this up with PyCryptodome maintainers...

Alternatively, if you can use (yet unreleased) pysnmp master, depending on your Python version, it would likely to depend on Cryptography rather than PyCryptodome.

**Comment by ICKGeek** [comment]
Ok Thanks. I will check this with PyCryptoodome maintainers.
Also, I will check this with pysnmp master branch also once

**Comment by ICKGeek** [comment]
Checking this with Pycryptodome maintainers. Hence closing this.
Thanks etingof for the help
