### ISSUE TITLE
SNMP v3 Localized keys not working or not explained how to use.

### ISSUE THREAD

**Issue by Runekeon** [etingof/pysnmp#288]
How do I localize keys 
```
ubuntu@sfager-dev:~$ snmpget -v3 -u <name>-a MD5 -3k <authKey> -x DES -3K <privKey> -l authPriv udp6:[2001:558:4053:4b:2e1d:b8ff:fe3c:b8c6] .1.3.6.1.2.1.1.1.0
iso.3.6.1.2.1.1.1.0 = STRING: "<<HW_REV: V1.0; VENDOR: Pace Micro Technology plc; BOOTR: 1_03; SW_REV: PX022AN_3.7p2s1_PROD_sey; MODEL: PX022ANC>>"
ubuntu@sfager-dev:~$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pysnmp import hlapi
>>> def snmp_print(errorIndication, errorStatus, errorIndex, varBinds):
    if errorIndication:
        print(errorIndication)
    elif errorStatus:
        print('%s at %s' % (errorStatus.prettyPrint(),
                            errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
    else:
        for varBind in varBinds:
            print(' = '.join([x.prettyPrint() for x in varBind]))
... 
>>> g = hlapi.nextCmd(hlapi.SnmpEngine(),
            hlapi.UsmUserData('<name>', authKey='<authKey>', privKey='<privKey>', authProtocol=hlapi.usmHMACMD5AuthProtocol , privProtocol=hlapi.usmDESPrivProtocol ),
            hlapi.Udp6TransportTarget(('2001:558:4053:4b:2e1d:b8ff:fe3c:b8c6', 161)),
            hlapi.ContextData(contextName='authPriv'),
            hlapi.ObjectType(hlapi.ObjectIdentity('.1.3.6.1.2.1.1.1.0')))
>>> errorIndication, errorStatus, errorIndex, varBinds = next(g)
>>> snmp_print(errorIndication, errorStatus, errorIndex, varBinds)
Wrong SNMP PDU digest
>>> 
```

**Comment by etingof** [comment]
Thank you for raising this!

Added in #295, your testing will be much appreciated!

**Comment by etingof** [comment]
FWIW, [snmpclitools](https://github.com/etingof/snmpclitools) piggy back this change and provide the same CLI interface as Net-SNMP tools do.

**Comment by Runekeon** [comment]
I tried using snmpclitools to test this and it raises an error:
Installed the new versions from repos
`$ sudo python3 -m pip freeze | grep  snmp
pysnmp==5.0.0
snmpclitools==0.6.4`
Normal SNMP command
`$ snmpget -v3 -u < user > -a MD5 -3k < defAuthLocalizedKey > -x DES -3K < defPrivLocalizedKey > -l authPriv udp6:[<IPv6>] .1.3.6.1.2.1.1.3.0 
iso.3.6.1.2.1.1.3.0 = Timeticks: (2949500) 8:11:35.00`
snmpclitools version
`$ snmpget.py -v3 -u < user > -l authPriv -a MD5 -3k < defAuthLocalizedKey > -x DES -3K < defPrivLocalizedKey > udp6:[<IPv6>] .1.3.6.1.2.1.1.3.0 
Process terminated
Traceback (most recent call last):;  File "/usr/local/bin/snmpget.py", line 99, in <module>;    secmod.generator((snmpEngine, ctx), ast);  File "/usr/local/lib/python3.4/dist-packages/snmpclitools/cli/secmod.py", line 420, in generator;    authKeyType = config.usmKeyTypeLocalized;AttributeError: 'module' object has no attribute 'usmKeyTypeLocalized';$`
Added debug
`$ snmpget.py -D all -v3 -u < user > -l authPriv -a MD5 -3k < defAuthLocalizedKey > -x DES -3K < defPrivLocalizedKey > udp6:[<IPv6>] .1.3.6.1.2.1.1.3.0 
2019-08-05 15:46:50,250 pysnmp: running pysnmp version 4.4.10
2019-08-05 15:46:50,250 pysnmp: debug category 'all' enabled
Process terminated
Traceback (most recent call last):;  File "/usr/local/bin/snmpget.py", line 99, in <module>;    secmod.generator((snmpEngine, ctx), ast);  File "/usr/local/lib/python3.4/dist-packages/snmpclitools/cli/secmod.py", line 420, in generator;    authKeyType = config.usmKeyTypeLocalized;AttributeError: 'module' object has no attribute 'usmKeyTypeLocalized';$`

**Comment by etingof** [comment]
You should use pysnmp from `release-4.4.11` branch.

**Comment by Runekeon** [comment]
I think part of the issue is that 4.4.10 didn't get removed completely. I had to rm the dirs, pip uninstall didn't remove them. Then reinstall the repo and I get different output.
`$ snmpget.py -D all -v3 -u < user > -l authPriv -a MD5 -3k < defAuthLocalizedKey > -x DES -3K < defPrivLocalizedKey > udp6:[<IPv6>] .1.3.6.1.2.1.1.3.0 
Traceback (most recent call last):
  File "/usr/local/bin/snmpget.py", line 23, in <module>
    from snmpclitools.cli import secmod
  File "/usr/local/lib/python3.4/dist-packages/snmpclitools/cli/secmod.py", line 14, in <module>
    'MD5': config.usmHMACMD5AuthProtocol,
AttributeError: 'module' object has no attribute 'usmHMACMD5AuthProtocol'
$`
I found this for using pip to install from GitHub with a branch or commit
https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip
I couldn't get them to work for the 4.4.11 branch or its last commit.
`$ python3 -m pip install -e git+https://github.com/etingof/pysnmp.git@release-4.4.11
--editable=git+https://github.com/etingof/pysnmp.git@release-4.4.11 is not the right format; it must have #egg=Package
Storing debug log for failure in /home/ezort/.pip/pip.log
$ python3 -m pip install -e git+https://github.com/etingof/pysnmp.git@89d14d560a00f2ac1ab7228f00e0edbeedb31808
--editable=git+https://github.com/etingof/pysnmp.git@89d14d560a00f2ac1ab7228f00e0edbeedb31808 is not the right format; it must have #egg=Package
Storing debug log for failure in /home/ezort/.pip/pip.log
$`
Tried adding the egg=pysnp and got this.
`$ python3 -m pip install -e git+https://github.com/etingof/pysnmp.git@release-4.4.11#egg=pysnmp
Obtaining pysnmp from git+https://github.com/etingof/pysnmp.git@release-4.4.11#egg=pysnmp
  Cloning https://github.com/etingof/pysnmp.git (to release-4.4.11) to ./src/pysnmp
  Running setup.py (path:/home/ezort/ezort/python/src/pysnmp/setup.py) egg_info for package pysnmp
    no previously-included directories found matching 'docs/build'
  Installing extra requirements: 'egg'
Requirement already satisfied (use --upgrade to upgrade): pysmi in /usr/local/lib/python3.4/dist-packages (from pysnmp)
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex in /usr/local/lib/python3.4/dist-packages (from pysnmp)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.2.3 in /usr/local/lib/python3.4/dist-packages (from pysnmp)
Installing collected packages: pysnmp
  Running setup.py develop for pysnmp
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/test-easy-install-5354.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /usr/local/lib/python3.4/dist-packages/
    
    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.
    
    For information on other options, you may wish to consult the
    documentation at:
    
      https://setuptools.readthedocs.io/en/latest/easy_install.html
    
    Please make the appropriate changes for your system and try again.
    
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize; __file__='/home/ezort/ezort/python/src/pysnmp/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    running develop

error: can't create or remove files in install directory



The following error occurred while trying to add or remove files in the

installation directory:



    [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/test-easy-install-5354.write-test'



The installation directory you specified (via --install-dir, --prefix, or

the distutils default setting) was:



    /usr/local/lib/python3.4/dist-packages/



Perhaps your account does not have write access to this directory?  If the

installation directory is a system-owned directory, you may need to sign in

as the administrator or "root" account.  If you do not have administrative

access to this machine, you may wish to choose a different installation

directory, preferably one that is listed in your PYTHONPATH environment

variable.



For information on other options, you may wish to consult the

documentation at:



  https://setuptools.readthedocs.io/en/latest/easy_install.html



Please make the appropriate changes for your system and try again.



----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize; __file__='/home/ezort/ezort/python/src/pysnmp/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps failed with error code 1 in /home/ezort/ezort/python/src/pysnmp
Storing debug log for failure in /home/ezort/.pip/pip.log
$`

**Comment by etingof** [comment]
It appears like you are trying to install a package into system directory while not being root...

The best thing would be to create a virtualenv and install everything into it:

```
python3.4 -m venv venv
. venv/bin/activate
pip install pip -U
git clone https://github.com/etingof/snmpclitools.git
cd snmpclitools
pip install .
```

**Comment by Runekeon** [comment]
I followed the above
`$ python3.4 -m venv venv
$ . venv/bin/activate
(venv) $ pip install pip -U
Downloading/unpacking pip from https://files.pythonhosted.org/packages/62/ca/94d32a6516ed197a491d17d46595ce58a83cbb2fca280414e57cd86b84dc/pip-19.2.1-py2.py3-none-any.whl#sha256=80d7452630a67c1e7763b5f0a515690f2c1e9ad06dda48e0ae85b7fdf2f59d97
  Downloading pip-19.2.1-py2.py3-none-any.whl (1.4MB): 1.4MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed pip
Cleaning up...
(venv) $ git clone https://github.com/etingof/snmpclitools.git
Cloning into 'snmpclitools'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 1178 (delta 2), reused 7 (delta 2), pack-reused 1165
Receiving objects: 100% (1178/1178), 229.21 KiB | 0 bytes/s, done.
Resolving deltas: 100% (721/721), done.
Checking connectivity... done.
(venv) $ cd snmpclitools
(venv) $ pip install .
Processing /home/ezort/ezort/python/snmpclitools
Collecting pysmi<0.4.0,>=0.3.4 (from snmpclitools==0.6.4)
  Downloading https://files.pythonhosted.org/packages/1f/fc/02361d1c2b247de73070c457c4da98c448693154894c14f2d7b48dfabf7e/pysmi-0.3.4-py2.py3-none-any.whl (80kB)
     |████████████████████████████████| 81kB 4.0MB/s 
Collecting pysnmp<5.0.0,>=4.4.4 (from snmpclitools==0.6.4)
  Downloading https://files.pythonhosted.org/packages/5d/5b/4b195bd3850ace4191277a8ca4b9442fc5c95051bdff7338baf9277ddebd/pysnmp-4.4.10-py2.py3-none-any.whl (294kB)
     |████████████████████████████████| 296kB 7.6MB/s 
Collecting ply (from pysmi<0.4.0,>=0.3.4->snmpclitools==0.6.4)
  Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)
     |████████████████████████████████| 51kB 12.1MB/s 
Collecting pycryptodomex (from pysnmp<5.0.0,>=4.4.4->snmpclitools==0.6.4)
  Downloading https://files.pythonhosted.org/packages/e4/83/f7f2f8514fbe014b372f4fff4023c6fae8b8685b9d9210ec3cbc27d449ee/pycryptodomex-3.8.2-cp34-cp34m-manylinux1_x86_64.whl (9.6MB)
     |████████████████████████████████| 9.6MB 17.4MB/s 
Collecting pyasn1>=0.2.3 (from pysnmp<5.0.0,>=4.4.4->snmpclitools==0.6.4)
  Downloading https://files.pythonhosted.org/packages/6a/6e/209351ec34b7d7807342e2bb6ff8a96eef1fd5dcac13bdbadf065c2bb55c/pyasn1-0.4.6-py2.py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 15.9MB/s 
Installing collected packages: ply, pysmi, pycryptodomex, pyasn1, pysnmp, snmpclitools
  Running setup.py install for snmpclitools ... done
Successfully installed ply-3.11 pyasn1-0.4.6 pycryptodomex-3.8.2 pysmi-0.3.4 pysnmp-4.4.10 snmpclitools-0.6.4
(venv) $ `

No change to the output:
`(venv) $ snmpget.py -v3 -u docsisManager -a MD5 -3k a3caabe7c0e32c9462c39e6e225f34fc -x DES -3K 9e9f41315e04c33c12958fcd6a572861 -l authPriv udp6:[2001:558:4053:4b:2e1d:b8ff:fe3c:b8c6] .1.3.6.1.2.1.1.3.0
Process terminated
Traceback (most recent call last):;  File "/home/ezort/ezort/python/venv/bin/snmpget.py", line 99, in <module>;    secmod.generator((snmpEngine, ctx), ast);  File "/home/ezort/ezort/python/snmpclitools/snmpclitools/cli/secmod.py", line 420, in generator;    authKeyType = config.usmKeyTypeLocalized;AttributeError: 'module' object has no attribute 'usmKeyTypeLocalized';(venv) $ 
(venv) $ python
Python 3.4.3 (default, Nov 12 2018, 22:25:49) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysnmp
>>> pysnmp.__version__
'4.4.10'
>>> 
(venv) $ pip freeze | grep  snmp
pysnmp==4.4.10
snmpclitools==0.6.4
(venv) $ 
`

Looks like snmpclitools pulled 4.4.10

**Comment by Runekeon** [comment]
Looks like snmpclitools pulled 4.4.10
```
(venv) $ snmpget.py -D all -v3 -u <user> -a MD5 -3k <defAuthLocalizedKey> -x DES -3K <defPrivLocalizedKey> -l authPriv udp6:[<IPv6>] .1.3.6.1.2.1.1.3.0
2019-08-05 19:00:05,911 pysnmp: running pysnmp version 4.4.10
2019-08-05 19:00:05,911 pysnmp: debug category 'all' enabled
Process terminated
Traceback (most recent call last):;  File "/home/ezort/ezort/python/venv/bin/snmpget.py", line 99, in <module>;    secmod.generator((snmpEngine, ctx), ast);  File "/home/ezort/ezort/python/snmpclitools/snmpclitools/cli/secmod.py", line 420, in generator;    authKeyType = config.usmKeyTypeLocalized;AttributeError: 'module' object has no attribute 'usmKeyTypeLocalized';(venv) $ 

(venv) $ python
Python 3.4.3 (default, Nov 12 2018, 22:25:49) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysnmp
>>> pysnmp.__version__
'4.4.10'
>>> 
(venv) $ pip freeze | grep  snmp
pysnmp==4.4.10
snmpclitools==0.6.4
(venv) $ 
```

**Comment by etingof** [comment]
Yes, that's what pip output above confirms... Well, try installing it by hand into your virtualenv:

```
pip install git+https://github.com/etingof/pysnmp@release-4.4.11 -U
```

**Comment by Runekeon** [comment]
Ran it like this after doing the above because the output was so large see attached file.
```
(venv) $ snmpget.py -D all -v3 -u <user> -a MD5 -3k <defAuthLocalizedKey> -x DES -3K <defPrivLocalizedKey> -l authPriv udp6:[<IPv6>] .1.3.6.1.2.1.1.3.0 > snmpget.py.test1.log 2>snmpget.py.test1.err
(venv) $ 
```
[snmpget.py.test1.err.txt](https://github.com/etingof/pysnmp/files/3469018/snmpget.py.test1.err.txt)

The log file was empty. I was able to get the uptime from the device with same creds right after the above.
and thanks for the hand-holding.

**Comment by etingof** [comment]
If you want to debug the keys part specifically, change `-D all` for `-D secmod`. Otherwise, is it working as expected or not quite yet?

**Comment by Runekeon** [comment]
still giving the "Wrong SNMP PDU digest" message instead of the uptime.

**Comment by etingof** [comment]
You should specify remote SNMP engine ID via `-e` option because when you bypassing password-based key configuration, you inactivate SNMP engine ID discovery mechanism as a side effect.

**Comment by Runekeon** [comment]
I did a find and replace on that stuff in the file before posting it but they could still be there in another form.
I tried the `-e` option with an empty string and didn't work. I don't have to add that in the regular command so not sure what that should be.

**Comment by etingof** [comment]
You should use `-e` option with the actual SNMP engine ID of your peer. That's only required for localized keys:

```
$ snmpget.py   -v3 -e 0x80004fb805636c6f75644dab22cc   -u usr-md5-des -l authPriv -3k 0x6b99c475259ef7976cf8d028a3381eeb -3K 0x92b5ef98f0a216885e73944e58c07345  demo.snmplabs.com sysDescr.0
SNMPv2-MIB::sysDescr.0 = DisplayString: Linux zeus 4.8.6.5-smp #2 SMP Sun Nov 13 14:58:11 CDT 2016 i686 
```

For master keys, SNMP engine ID discovery would work:

```
$ snmpget.py  -v3 -u usr-md5-des -l authPriv -3m 0x1dcf59e86553b3afa5d32fd5d61bf0cf  -3M 0xec5ab55e93e1d85cb6846d0f23e845e0  demo.snmplabs.com sysDescr.0 
SNMPv2-MIB::sysDescr.0 = DisplayString: Linux zeus 4.8.6.5-smp #2 SMP Sun Nov 13 14:58:11 CDT 2016 i686 
```

You can figure out your peer SNMP engine ID by running `snmpget -D secmod`, it will be present in response messages and reported in the log. 

I guess Net-SNMP tools are optimized for this single-command use-case. So they assume that if localized key is given and no security engine ID is present, then they have just one peer SNMP engine so that they always use the same localized keys against any target.

That works for a command-line testing tool, however not for a generally applicable SNMP engine which can easily have many SNMP peers configured differently. That requires each peer configured individually.

Does it make sense? Would it be a nuisance in your situation to pin remote SNMP engine ID?

**Comment by Runekeon** [comment]
I will check but we work with 10 of millions of devices like this and I can't remember ever setting the engine ID. I would probably stick with using system call if it takes an extra action and parsing to get.

**Comment by etingof** [comment]
Ah, I see. Let me see how it's done in Net-SNMP... This whole localized keys deal is quite a hack. to be honest. I do not see it ever mentioned in RFCs.

What do you mean, sticking to the system call?

**Comment by Runekeon** [comment]
right now the code I have is using subprocess with a composed string to do the SNMP command as if I was typing it on cli in Linux.

**Comment by Runekeon** [comment]
I was able to get the engineId from the trace and then the code does work.

**Comment by Runekeon** [comment]
I check another device and it has a different engine id.

**Comment by Runekeon** [comment]
FYI I belive the localized keys are from RFC2786.

**Comment by etingof** [comment]
> FYI I belive the localized keys are from RFC2786.

I need to read that, but I have doubts - it talks about [Diffie–Hellman key exchange](https://en.wikipedia.org/wiki/Diffie–Hellman_key_exchange) while what we do is skipping both stages of key localization which is just double hashing.

But that would be interesting to implement, thanks for the pointer!

**Comment by etingof** [comment]
> I check another device and it has a different engine id.

This is good! It's supposed to be unique.

**Comment by etingof** [comment]
Consider trying [this branch](https://github.com/etingof/pysnmp/tree/wildcard-engine-id). Also see #297 for technical details.

**Comment by etingof** [comment]
Out of curiosity, why do you want to skip key localization? Is it a performance issue?

**Comment by Runekeon** [comment]
I get the localized keys from a service our security team owns. They have different passwords, randoms, and salts for each model which they change regularly.  I won't have any way to SNMP these devices without using localized keys in about 3 weeks when v2 is turned off.

**Comment by Runekeon** [comment]
The wildcard-engine-id works!
(venv) $ snmpget.py -e 0x0000000000 -v3 -u <securityname> -a MD5 -3k <authKey> -x DES -3K <privKey> -l authPriv udp6:[<ip>] .1.3.6.1.2.1.1.3.0
SNMPv2-MIB::sysUpTime.0 = TimeTicks: 0 days 11:16:44.0 
(venv) $

Thanks :)

**Comment by etingof** [comment]
FYI, I've extracted and published [master and localized keys](http://snmplabs.com/snmp-simulation-service.html#master-and-localized-keys) for the on-line SNMP simulator. Hope that could be helpful for testing.

**Comment by etingof** [comment]
FYI: `snmpclitools` now add that magic five-zeros security engine ID to local configuration automatically making `snmp*.py` behaving similar to Net-SNMP `snmp*` tools.

**Comment by etingof** [comment]
FIY: `pysnmp 4.4.11` and `snmpclitools 0.6.4` have been released. The feature discussed here is included in these release.

**Comment by etingof** [comment]
Added [hlapi example](http://snmplabs.com/pysnmp/examples/hlapi/asyncore/sync/manager/cmdgen/advanced-topics.html#snmpv3-localized-auth-and-privacy-keys) to ease feature adoption.
