### ISSUE TITLE
Is SNMP TRAP Notification source address spoofing possible?

### ISSUE THREAD

**Issue by amartiresST** [etingof/pysnmp#289]
Hi, 
I need to develop a script that generates snmp traps from syslog messages and I was thinking that maybe I could pass the syslog message to a python script that would generate a snmp trap, but I need the trap to have the original message host address and not the syslog server address.

Is it possible to spoof the source address when sending a notification with pysnmp?

Thanks!

**Comment by etingof** [comment]
Hey, yes! This should work at least on UNIX and if you are not using asyncio. Here is [an example](http://snmplabs.com/pysnmp/examples/v3arch/asyncore/manager/cmdgen/transport-tweaks.html#spoof-source-address) for SNMP GET, but it should be similar for notifications.

**Comment by amartiresST** [comment]
Thanks a lot @etingof!
I think I got the gist of it.

I'm having some trouble finding how to replace this part in order to send a TRAP Notification...
```
# Prepare and send a request message
cmdgen.GetCommandGenerator().sendVarBinds(
    snmpEngine,
    'my-router',
    None, '',  # contextEngineId, contextName
    [((1, 3, 6, 1, 2, 1, 1, 1, 0), None)],
    cbFun
)
```
I suppose I need to generate a command for sending a trap, but I can't seem to find and adequate class.

Am I on the wrong path here?
Can you give me some clue?

**Comment by etingof** [comment]
Look for [notification originator](http://snmplabs.com/pysnmp/examples/v3arch/asyncore/contents.html#notification-originator-applications) - that's the SNMP parlance.

**Comment by amartiresST** [comment]
@etingof, I will look into that.
Thanks!

**Comment by amartiresST** [comment]
I got it to work.

Basically all I needed to do was to add the _sourceAddress=('1.2.3.4', 0)_ to config.addTargetAddr()
following the example in the [notification originator](http://snmplabs.com/pysnmp/examples/v3arch/asyncore/agent/ntforg/snmp-versions.html#snmpv2c-trap).

Thanks a lot for you help!
Cheers!

**Comment by etingof** [comment]
Awesome!
