### ISSUE TITLE
Help sending RowStatus style complex varbinds

### ISSUE THREAD

**Issue by coxoperationsengineer** [etingof/pysnmp#293]
Python 3.7
pysnmp = 4.4.10
all updates to dependencies installed fresh today

Hey guys,

I am working on a project where I need to do some semi-complex SNMP SET's on about 5,000 hosts. I have worked out the MIB's, and got it working via linux console/net-snmp but I would ideally like to make this a python friendly script so that I can turn the project into an .exe that can run on Windows so others can help do a chunk of the hosts.  I have gotten PySNMP working for GET's, but SET's seem to fail no matter how simple of one I try to do, can someone show me the structure of a request like this?

I do have the mib files from the vendor available, in venv\\lib\\site-packages\\pysnmp\\smi\\mibs but they are not converted to .py, I see varying reports as to needing to do that or not.  But I do keep getting pysnmp.smi.error.MibNotFoundError: TIMETRA-LOG-MIB compilation error(s)     I just wasn't sure if its because I'm doing something wrong in the code or not.

Linux command that does work
`snmpset -v2c -c fakecommstring 172.22.22.22 tmnxSyslogTargetRowStatus.3 i 4 tmnxSyslogTargetDescription.3 s "Syslog Server 98.0.0.0" tmnxSyslogTargetFacility.3 i 17 tmnxSyslogTargetMessagePrefix.3 s "hostname" tmnxSyslogTargetAddrType.3 i 1 tmnxSyslogTargetAddr.3 x "62 B6 01 B6"`

Syslog MIBs converted to OID's in case that is easier syntactically
  tmnxSyslogTargetRowStatus.3 = .1.3.6.1.4.1.6527.3.1.2.12.8.1.2.3
  tmnxSyslogTargetDescription.3 = .1.3.6.1.4.1.6527.3.1.2.12.8.1.3.3
  tmnxSyslogTargetFacility.3 = .1.3.6.1.4.1.6527.3.1.2.12.8.1.6.3
  tmnxSyslogTargetMessagePrefix.3 = .1.3.6.1.4.1.6527.3.1.2.12.8.1.8.3
  tmnxSyslogTargetAddrType.3 = .1.3.6.1.4.1.6527.3.1.2.12.8.1.10.3
  tmnxSyslogTargetAddr.3 = .1.3.6.1.4.1.6527.3.1.2.12.8.1.11.3

# Sample Output
```
snmpwalk -v2c -c fakecomm 172.22.22.22 tmnxSyslogTargetTable | grep "\.3 = "
TIMETRA-LOG-MIB::tmnxSyslogTargetRowStatus.3 = INTEGER: active(1)
TIMETRA-LOG-MIB::tmnxSyslogTargetDescription.3 = STRING: "Syslog Server 98.0.0.0"
TIMETRA-LOG-MIB::tmnxSyslogTargetUdpPort.3 = INTEGER: 514
TIMETRA-LOG-MIB::tmnxSyslogTargetFacility.3 = INTEGER: local1(17)
TIMETRA-LOG-MIB::tmnxSyslogTargetSeverity.3 = INTEGER: info(6)
TIMETRA-LOG-MIB::tmnxSyslogTargetMessagePrefix.3 = STRING: "hostname"
TIMETRA-LOG-MIB::tmnxSyslogTargetMessagesDropped.3 = Counter32: 0
TIMETRA-LOG-MIB::tmnxSyslogTargetAddrType.3 = INTEGER: ipv4(1)
TIMETRA-LOG-MIB::tmnxSyslogTargetAddr.3 = Hex-STRING: 62 B6 01 B6
```

**Comment by etingof** [comment]
That should totally work with pysnmp as soon as you [give it](http://snmplabs.com/pysnmp/examples/hlapi/asyncore/sync/manager/cmdgen/mib-tweaks.html#custom-asn-1-mib-path) the MIB(s) you refer to.

You do not **have to** compile any MIBs, that will happen automatically. However if you want to eliminate `pysmi` dependencies, you can compile all MIBs you need by hand with [mibdump](http://snmplabs.com/pysmi/mibdump.html) tool from the `pysmi` package. Then copy *.py MIBs to `~/.pysnmp/mibs` (that's the default) so pysnmp will pick it up from there.

**Comment by coxoperationsengineer** [comment]
Thank you for the examples, I was indeed able to get this working by providing the OID's rather than the MIB's.  I didn't have to go the async route, even single threaded sending all those updates, as long as I checked that the host was responding first, and only sent it to responding hosts, I was doing roughly 15 hosts a second!
