### ISSUE TITLE
v3 inform notification receiver , from multiple snmp-agents

### ISSUE THREAD

**Issue by prathapk1990** [etingof/pysnmp#294]
Hi @etingof 

Are there any examples for receiving notifications from multiple inform sources(snmp v3).

I have requirement explained below,

```v3-inform-receiver ----- connected to multiple (routers, sending v3 informs)```

I am trying to build receiver app, with single transport which can listen to all the incoming v3 informs and process the varbinds.

Thanks .

**Comment by etingof** [comment]
I think you can just remove extra `addV3User` calls from [this example](http://snmplabs.com/pysnmp/examples/v3arch/asyncore/manager/ntfrcv/snmp-versions.html#multiple-snmp-usm-users) and it should work out of the box.

You need a single transport (socket), one or more (depending on your requirements) USM usernames. If you need to distinguish your peers by network address, [this example](http://snmplabs.com/pysnmp/examples/v3arch/asyncore/manager/ntfrcv/advanced-topics.html#observe-snmp-engine-internal-operations) explains that.

**Comment by prathapk1990** [comment]
@etingof Thanks for the suggestions,

are there any scale numbers we have against pysnmp performance, such as
* how many notifications receiver can handle
* max number of usm users per transport

any other best practices captured somewhere, would help.

**Comment by etingof** [comment]
Performance greatly depends on so many factors that it's practically impossible to estimate. You should prototype your application and run some performance tests against it.

There is no explicit limitation on USM user DB size.

**Comment by prathapk1990** [comment]
Thank you very much, appreciate your effort in helping out with my queries @etingof
