### ISSUE TITLE
Implementing custom scalar Mib objects

### ISSUE THREAD

**Issue by elcfd** [etingof/pysnmp#299]
Hi,

I am implementing my own custom scalar Mib object and would like to understand the behavior that I am seeing. Following the guide here [implementing-scalar-mib-objects](http://snmplabs.com/pysnmp/examples/v3arch/asyncore/agent/cmdrsp/agent-side-mib-implementations.html#implementing-scalar-mib-objects) I have my Mib implementation up and running and can query the agent as expected.

However, if I move the following code into its own module:

```python
class MyStaticMibScalarInstance(MibScalarInstance):
    # noinspection PyUnusedLocal,PyUnusedLocal
    def getValue(self, name, idx):
        return self.getSyntax().clone(
            'Python %s running on a %s platform' % (sys.version, sys.platform)
        )
```

and import the MibScalarInstance definition, in the same module, as so:

```python
from pysnmp.smi.builder import MibBuilder

MibScalarInstance, = MibBuilder().importSymbols('SNMPv2-SMI', 'MibScalarInstance') 
```

When, back in the my SNMP engine's code, I export my symbol I can no longer snmpget or snmpwalk MyStaticMibScalarInstance - I receive the following response:

```
 No Such Object available on this agent at this OID
```

The method that I am currently using, is to import the MibScalarInstance SNMPv2-SMI symbol using the MibBuilder attached to my SNMP Engine:

```python
     self.snmp_engine = engine.SnmpEngine()
     self.snmp_context = context.SnmpContext(self.snmp_engine)
     self.mib_builder = self.snmp_context.getMibInstrum().getMibBuilder()
     self.mib_scalar, self.mib_scalar_instance, = self.mib_builder.importSymbols(
         'SNMPv2-SMI', 'MibScalar', 'MibScalarInstance')
``` 

Then, in the separate module where I have my custom scalar Mib object using a function to subclass the MibScalarInstance definition:

```python
def create_custom_mib_scalar_instance(superclass, name):

    class MyStaticMibScalarInstance(superclass):

        maxAccess = 'readWrite'

        def __init__(self, name):

            super(MyStaticMibScalarInstance, self).__init__(
                      name, (0,), v2c.OctetString())

        # noinspection PyUnusedLocal,PyUnusedLocal
        def getValue(self, name, idx):
            return self.getSyntax().clone(
                'Python %s running on a %s platform' % (sys.version, sys.platform)
            )

    return MyStaticMibScalarInstance(name)
```

Finally, back in the SNMP engine code I can do the following:

```python
 self.mib_builder.exportSymbols(
            '__MY_MIB',
            self.mib_scalar((1, 3, 6, 1, 5, 2), v2c.OctetString()),
            create_custom_mib_scalar_instance(
                self.mib_scalar_instance, (1, 3, 6, 1, 5, 2))
)
``` 

and I can successfully snmpget my custom scalar Mib object:

```
iso.3.6.1.5.2.0 = STRING: "Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0] running on a linux2 platform"
```

Would you kindly explain the behavior I am seeing and whether the function/subclass approach is best?

**Comment by etingof** [comment]
I am not sure about this line:

    MibScalarInstance, = MibBuilder().importSymbols('SNMPv2-SMI', 'MibScalarInstance') 

Because that way this `MibScalarInstance` might no longer be considered to belong to the whole inheritance chain of the SMI objects as imported by the other `MibBuilder` (e.g. the default one, instantiated by `SnmpEngine`. Also, your objects might reside in a different (parallel) MIB tree so SNMP engine does not see it.

Therefore I'd rather use the `mibBuilder` instance [as passed by the parent](https://github.com/etingof/pysnmp/blob/master/pysnmp/smi/mibs/instances/__PYSNMP-USM-MIB.py#L10).

**Comment by elcfd** [comment]
Thank you for the explanation - as you said I was splitting the trees.
