### ISSUE TITLE
Simple issue in documentation

### ISSUE THREAD

**Issue by GilaAquila** [etingof/pysnmp#3]
I found that in the example listed here: http://pysnmp.sourceforge.net/docs/hlapi/asyncore/sync/manager/cmdgen/nextcmd.html you are using the async library and trying to execute it with sync API.

**Comment by GilaAquila** [comment]
I see that this issue is repeated almost in every synchronized example in that documentation

**Comment by etingof** [comment]
Fixed, thanks!
