### ISSUE TITLE
Equivalent of value.isSameTypeWith(NoSuchInstance()) in pysnmp.hlapi.asyncore?

### ISSUE THREAD

**Issue by coxoperationsengineer** [etingof/pysnmp#303]
Hello,

I am using the following in the standard library, and I have moved towards trying the asyncore library for speed gains as I am querying 2-3k hosts.  I can't seem to find a suitable way to duplicate the following, where I want to write out to a text file any host that didn't have the OID(s) set by returning that string object.  I am open to a different export method or approach, but given the target list size, I need to quickly be able to determine which ones DID NOT work, so I can review those manually.

    from pysnmp.hlapi import *  (the non async library allows me to use this)
    for oid, value in varBinds:
        if value.isSameTypeWith(NoSuchInstance()) or value.isSameTypeWith(NoSuchObject()):
            print('object {oid} does not exist at {ipAddress}'.format(oid=oid, ipAddress=ipAddress))
                    return str(ipAddress + " - OID was missing during validation")
        else:
            print('Check was good for {oid}'.format(oid=oid))

Here is my code that I am using for reference on the asyncore setup, also since this is my first stab at an async script, should I open the text file for writing in main() and return the result on each call or where does that best fit from an efficiency standpoint?

    import csv
    import time
    from datetime import datetime
    
    from pysnmp.hlapi.asyncore import *
    
    
    # Wait for responses or errors
    # noinspection PyUnusedLocal,PyUnusedLocal
    def cbFun(snmpEngine, sendRequestHandle, errorIndication,
              errorStatus, errorIndex, varBinds, cbCtx):
        transportTarget = cbCtx
        print('%s' % transportTarget)
    
        if errorIndication:
            print(errorIndication)
            return True
        elif errorStatus:
            print('%s at %s' % (errorStatus.prettyPrint(),
                                errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
            return True
        else:
            for varBind in varBinds:
                print(' = '.join([x.prettyPrint() for x in varBind]))
    
    
    if __name__ == '__main__':
    
        start = datetime.now()
        targets = []
    
        with open('C:\\temp\\SERSysLog\\test.csv') as routerFile:
            routerDict = csv.DictReader(routerFile)
            for row in routerDict:
                # List of targets in the following format:
                # ( ( authData, transportTarget, varNames ), ... )
                targets.append(
                    # 1-st target (SNMPv2 over IPv4/UDP)
                    (CommunityData('COMMSTRINGHERE'),
                     UdpTransportTarget((row['IP'], 161)),
                     (ObjectType(ObjectIdentity('1.3.6.1.4.1.6527.3.1.2.12.8.1.2.3')),
                      ObjectType(ObjectIdentity('1.3.6.1.4.1.6527.3.1.2.12.5.1.2.45')))),
                )
        print(f'We loaded in {len(targets)} targets - Standby')
    
        # Create SNMP Engine instance
        snmpEngine = SnmpEngine()
    
        # Submit GET requests
        for authData, transportTarget, varNames in targets:
            getCmd(snmpEngine, authData, transportTarget, ContextData(), *varNames,
                   **dict(cbFun=cbFun, cbCtx=transportTarget))
        snmpEngine.transportDispatcher.runDispatcher()
    
        end = datetime.now()
        time_taken = end - start
        print('Time Elapsed in (%H:%M:%S):', time_taken)

**Comment by etingof** [comment]
If I understand you correctly, your only issue is how to get hold of the `NoSuchInstance` error indicator, is that correct?

The `NoSuchObject` or `NoSuchInstance` classes and instances are available from [pysnmp.proto.rfc1905](https://github.com/etingof/pysnmp/blob/master/pysnmp/proto/rfc1905.py#L39), however you can also just import them from `pysnmp.hlapi` as you do with the sync version.

Once you have these sentinels in place, you can probably perform the same treatment inside the `for` loop over `varBinds` in your async code as you've don in the sync version.

Does it make sense? Let me know if I misread your comment.

**Comment by coxoperationsengineer** [comment]
Yes you are understanding perfectly, and you gave me a good clue, I was able to import those items from that RFC file, so that takes care of one aspect.

I am now am embarrassingly having troubles figuring out how to return something in the async function to a text file, mainly in the sense I'm not sure where to catch the returns period, as the async stuff is very new to me.  Do you have any examples?  Outside of returning the results in the varBinds, I need to catch the errorIndications, as I think those are triggered from dead hosts, or in my case, bad commstrings, so I need to have a backup commstring to try on those.  I will likely just send those to a text file on their own and just run the list again with a better commstring to keep it simple for version 1.0.

I really wanted to use Asyncio since the documentation in general outside of just this library is pretty plentiful, but I guess there is some bug with Windows 10, Asyncio and Python 3.7, where it never opens the sockets/connects.

**Comment by etingof** [comment]
> how to return something in the async function to a text file, mainly in the sense I'm not sure where to catch the returns period

I am not sure I understand your confusion here... Can you just append stuff to a text file from the callback function?

If you need to keep some state (e.g. data from previous responses), the usual way is to utilize the `cbCtx` reference. If can be anything that you pass to your initial query, then this very same object will always be available in the callback function. For example, it can be a dict with your own keys referring to something you need to pass in and/or out of the callback function.

**Comment by coxoperationsengineer** [comment]
Ah ok, so doing something like this is acceptable?  I wasn't sure if it was this simple or if I was going to cause blocking by doing it this way, as I assume I am opening the file to append as many times as I have hosts.   Also, if I hit the errorIndication, is there a way to easily switch the commstring out for the additional retry attempts?   Thank you for your help with this, it is very fast, 2,000 hosts in 14 seconds fast. 

    def cbFun(snmpEngine, sendRequestHandle, errorIndication, errorStatus,
          errorIndex, varBinds, cbCtx):

    transportTarget = cbCtx

    # Open a text file for results
    with open('C:\\temp\\test_validation.txt', 'a') as f:

    # Let them know what host we are starting on
    print(f'Starting on {transportTarget}')

    if errorIndication:
      print(errorIndication)
      return True
    elif errorStatus:
      print('%s at %s' %
            (errorStatus.prettyPrint(),
             errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
      return True
    else:
      for oid, value in varBinds:
        if value.isSameTypeWith(NoSuchInstance()) or value.isSameTypeWith(NoSuchObject()):
          results = (
              f'{transportTarget} - OID was was not located for this host\n'
          )
          # Write the results out
          f.write(results)
        else:
          print('Check was good for {oid}'.format(oid=oid))
