### ISSUE TITLE
SNMPv1 get results ignored/dropped?

### ISSUE THREAD

**Issue by ww9rivers** [etingof/pysnmp#31]
Here is an test example (snmpget from Net-SNMP vs pysnmp 4.2.5-1 on Ubuntu 16.04.1):

$ snmpget -d -c public -v 1 10.23.65.65 .1.3.6.1.4.1.29660.2.3.2.0

Sending 47 bytes to UDP: [10.23.65.65]:161->[0.0.0.0]:0
0000: 30 2D 02 01  00 04 06 70  75 62 6C 69  63 A0 20 02    0-.....public. .
0016: 04 18 F3 6C  4B 02 01 00  02 01 00 30  12 30 10 06    ...lK......0.0..
0032: 0C 2B 06 01  04 01 81 E7  5C 02 03 02  00 05 00       .+......\......

Received 49 byte packet from UDP: [10.23.65.65]:161->[0.0.0.0]:36079
0000: 30 2F 02 01  00 04 06 70  75 62 6C 69  63 A2 22 02    0/.....public.".
0016: 04 18 F3 6C  4B 02 01 00  02 01 00 30  14 30 12 06    ...lK......0.0..
0032: 0C 2B 06 01  04 01 81 E7  5C 02 03 02  00 02 02 02    .+......\.......
0048: 35                                                    5

iso.3.6.1.4.1.29660.2.3.2.0 = INTEGER: 565

$ pysnmpget -d -c public -v 1 10.23.65.65 1.3.6.1.4.1.29660.2.3.2.0
DBG: [10:42:39.482]: running pysnmp version 4.2.5
DBG: [10:42:39.482]: debug category 'io' enabled
DBG: [10:42:39.496]: sendMessage: outgoingMessage queued (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:39.496]: handle_write: transportAddress ('0.0.0.0', 0) -> ('10.23.65.65', 161) outgoingMessage (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:39.510]: handle_read: transportAddress ('10.23.65.65', 161) -> ('0.0.0.0', 42116) incomingMessage (48 octets)
00000: 30 2E 02 01 00 04 06 70 75 62 6C 69 63 A2 21 02
00016: 03 17 11 34 02 01 00 02 01 00 30 14 30 12 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 02 02 02 35
DBG: [10:42:40.514]: sendMessage: outgoingMessage queued (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:40.515]: handle_write: transportAddress ('0.0.0.0', 42116) -> ('10.23.65.65', 161) outgoingMessage (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:40.527]: handle_read: transportAddress ('10.23.65.65', 161) -> ('0.0.0.0', 42116) incomingMessage (48 octets)
00000: 30 2E 02 01 00 04 06 70 75 62 6C 69 63 A2 21 02
00016: 03 17 11 34 02 01 00 02 01 00 30 14 30 12 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 02 02 02 35
DBG: [10:42:41.532]: sendMessage: outgoingMessage queued (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:41.532]: handle_write: transportAddress ('0.0.0.0', 42116) -> ('10.23.65.65', 161) outgoingMessage (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:41.543]: handle_read: transportAddress ('10.23.65.65', 161) -> ('0.0.0.0', 42116) incomingMessage (48 octets)
00000: 30 2E 02 01 00 04 06 70 75 62 6C 69 63 A2 21 02
00016: 03 17 11 34 02 01 00 02 01 00 30 14 30 12 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 02 02 02 35
DBG: [10:42:42.547]: sendMessage: outgoingMessage queued (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:42.548]: handle_write: transportAddress ('0.0.0.0', 42116) -> ('10.23.65.65', 161) outgoingMessage (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:42.560]: handle_read: transportAddress ('10.23.65.65', 161) -> ('0.0.0.0', 42116) incomingMessage (48 octets)
00000: 30 2E 02 01 00 04 06 70 75 62 6C 69 63 A2 21 02
00016: 03 17 11 34 02 01 00 02 01 00 30 14 30 12 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 02 02 02 35
DBG: [10:42:43.563]: sendMessage: outgoingMessage queued (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:43.564]: handle_write: transportAddress ('0.0.0.0', 42116) -> ('10.23.65.65', 161) outgoingMessage (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:43.577]: handle_read: transportAddress ('10.23.65.65', 161) -> ('0.0.0.0', 42116) incomingMessage (48 octets)
00000: 30 2E 02 01 00 04 06 70 75 62 6C 69 63 A2 21 02
00016: 03 17 11 34 02 01 00 02 01 00 30 14 30 12 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 02 02 02 35
DBG: [10:42:44.580]: sendMessage: outgoingMessage queued (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:44.580]: handle_write: transportAddress ('0.0.0.0', 42116) -> ('10.23.65.65', 161) outgoingMessage (46 octets)
00000: 30 2C 02 01 00 04 06 70 75 62 6C 69 63 A0 1F 02
00016: 03 17 11 34 02 01 00 02 01 00 30 12 30 10 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 05 00
DBG: [10:42:44.594]: handle_read: transportAddress ('10.23.65.65', 161) -> ('0.0.0.0', 42116) incomingMessage (48 octets)
00000: 30 2E 02 01 00 04 06 70 75 62 6C 69 63 A2 21 02
00016: 03 17 11 34 02 01 00 02 01 00 30 14 30 12 06 0C
00032: 2B 06 01 04 01 81 E7 5C 02 03 02 00 02 02 02 35
No SNMP response received before timeout

**Comment by ww9rivers** [comment]
4.2.5-1 is not the latest version of pysnmp. Sorry.

**Comment by etingof** [comment]
Right, let me know if you still experience issues with the latest pysnmp/pysnmp-apps.

**Comment by ww9rivers** [comment]
No. Not anymore with 4.3.2 in Pypi. So I closed the issue on Github.

Thank you for looking into the issue.
