### ISSUE TITLE
Collecting the entire SNMP table

### ISSUE THREAD

**Issue by 631068264** [etingof/pysnmp#310]
I can use get result from localhost
```
root@dasheng:/etc/snmp# snmpwalk -v 2c -c public localhost IP-FORWARD-MIB::ipCidrRouteDest
IP-FORWARD-MIB::ipCidrRouteDest.0.0.0.0.0.0.0.0.0.10.130.0.1 = IpAddress: 0.0.0.0
IP-FORWARD-MIB::ipCidrRouteDest.10.130.0.0.255.255.252.0.0.0.0.0.0 = IpAddress: 10.130.0.0
IP-FORWARD-MIB::ipCidrRouteDest.10.130.0.1.255.255.255.255.0.0.0.0.0 = IpAddress: 10.130.0.1
IP-FORWARD-MIB::ipCidrRouteDest.172.17.0.0.255.255.0.0.0.0.0.0.0 = IpAddress: 172.17.0.0
IP-FORWARD-MIB::ipCidrRouteDest.172.18.0.0.255.255.0.0.0.0.0.0.0 = IpAddress: 172.18.0.0
IP-FORWARD-MIB::ipCidrRouteDest.172.19.0.0.255.255.0.0.0.0.0.0.0 = IpAddress: 172.19.0.0
```

But failed in code

```py
    iterator = getCmd(SnmpEngine(),
                      CommunityData('public'),
                      UdpTransportTarget(('locahost', 161)),
                      ContextData(),
                      # ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysUpTime', 0)),
                      ObjectType(ObjectIdentity('IP-FORWARD-MIB', 'ipCidrRouteDest',123)),
                      )

    errorIndication, errorStatus, errorIndex, varBinds = next(iterator)

    if errorIndication:  # SNMP engine errors
        print(errorIndication)
    else:
        if errorStatus:  # SNMP agent errors
            print('%s at %s' % (errorStatus.prettyPrint(), varBinds[int(errorIndex) - 1] if errorIndex else '?'))
        else:
            for varBind in varBinds:  # SNMP response contents
                print(' = '.join([x.prettyPrint() for x in varBind]))
```

And get
```
IP-FORWARD-MIB::ipCidrRouteDest = No Such Instance currently exists at this OID
```

**Comment by etingof** [comment]
Perhaps your node does not have such OID... Try [walking](http://snmplabs.com/pysnmp/examples/hlapi/asyncore/sync/manager/cmdgen/walking-operations.html) the entire table to see which entries are there.

**Comment by 631068264** [comment]
No, I have get info to use ip table info  by `IP-FORWARD-MIB::ipCidrRouteDest` by client in localhost . I have shown that in the first code block .  But when I use your lib, it can't get any thing.

**Comment by etingof** [comment]
Ah, right. But where `123` comes from? The proper indices can be seen in snmpwalk output e.g. `0.0.0.0.0.0.0.0.0.10.130.0.1` So try something like:

```
ObjectType(ObjectIdentity('IP-FORWARD-MIB', 'ipCidrRouteDest', '0.0.0.0', '0.0.0.0', 0, '10.130.0.1')),
```

The index is structured like this:

```
 INDEX {
           ipCidrRouteDest,
           ipCidrRouteMask,
           ipCidrRouteTos,
           ipCidrRouteNextHop
           }
          ::= { ipCidrRouteTable 1 }
```

**Comment by 631068264** [comment]
This is my mistake in code with `123`
![image](https://user-images.githubusercontent.com/8144089/65585545-38692400-dfb5-11e9-93db-c7db66f5ff44.png)

I want to get the whole ip table for the unknown machine  so where `'0.0.0.0', '0.0.0.0', 0, '10.130.0.1' ` come from .

**Comment by etingof** [comment]
These variable tail pieces are known as *indices* in SNMP. They might be dynamic meaning that SNMP agent would create and remove them at run time reflecting the changes to (in this case) the routing table.

Having said that, there is frequently no way to know the right index in advance. Therefore SNMP has the GETNEXT/GETBULK commands to enumerate all existing objects under a given OID prefix.

I suggest you to try [SNMP walking](http://snmplabs.com/pysnmp/examples/hlapi/asyncore/sync/manager/cmdgen/walking-operations.html) your unknown machine, collect all the entries it currently has and let your app figure out what to do with them.
