### ISSUE TITLE
minor mistake in privProtocol docs

### ISSUE THREAD

**Issue by jmgurney** [etingof/pysnmp#312]
Was reading through the docs at: http://snmplabs.com/pysnmp/docs/api-reference.html#pysnmp.hlapi.UsmUserData

and noticed that under privProtocol, it says:
usmNoPrivProtocol (default is authKey not given)
usmDESPrivProtocol (default if authKey is given)

I believe both of those authKey should be privKey instead.

**Comment by etingof** [comment]
Yes! Fixed. Thank you!

**Comment by etingof** [comment]
BTW, feel free to PR right away! ;-)
