### ISSUE TITLE
Where is the MIB file saved ?

### ISSUE THREAD

**Issue by ljy296566** [etingof/pysnmp#314]
if my PC cannot connect to the Internet, where should I save the MIB file ?

**Comment by etingof** [comment]
By default, compiled (into Python) MIBs are saved into `~/.pysnmp/mibs` (on UNIX).

You can also set non-default path for either compiled MIBs ([addMibSource](http://snmplabs.com/pysnmp/docs/api-reference.html#pysnmp.smi.rfc1902.ObjectIdentity.addMibSource)) or ASN.1 MIBs to be compiled whenever needed ([addAsn1MibSource](http://snmplabs.com/pysnmp/docs/api-reference.html#pysnmp.smi.rfc1902.ObjectIdentity.addAsn1MibSource)).
