### ISSUE TITLE
How to disconnect SNMP notification reciever UDP port

### ISSUE THREAD

**Issue by lukebond** [etingof/pysnmp#32]
I'm building a trap receiver based on this example: http://pysnmp.sourceforge.net/examples/current/v3arch/manager/ntfrcv/v3-multiple-users.html

I'm unable to get it to release the UDP port without exiting the application, which makes it difficult to start and stop in the setup and teardown of my tests.

If I run a `watch -n 1 'netstat -ulpn | grep 162'` as the tests run, I can see the port remains bound until the application exits, meaning that after multiple tests I have multiple servers bound to that port.

This is my current teardown code:

```
    ...
    self.snmpEngine.transportDispatcher.jobFinished(1)
    self.snmpEngine.transportDispatcher.unregisterRecvCbFun(recvId=None)
    self.snmpEngine.transportDispatcher.unregisterTransport(udp.domainName)
    self.snmpEngine.transportDispatcher.closeDispatcher()
    self.snmpEngine.unregisterTransportDispatcher(self.snmpEngine.transportDispatcher)
```

I'm basically calling every method that looks like it might do it, because I don't know what I'm doing :)

What am I missing to make it release the UDP port?

**Comment by etingof** [comment]
If I call  `self.snmpEngine.transportDispatcher.closeDispatcher()` with the latest released pysnmp, my netstat stops showing open port.

This is [where](https://github.com/etingof/pysnmp/blob/master/pysnmp/carrier/asyncore/base.py#L82) socket gets closed when invoked from [here](https://github.com/etingof/pysnmp/blob/master/pysnmp/carrier/base.py#L192).

**Comment by lukebond** [comment]
I've since worked around this by designing my tests differently and can't easily reproduce it. Shall we just assume I was mistaken and close it?

**Comment by etingof** [comment]
Sure! Thanks for using pysnmp! ;-)
