### ISSUE TITLE
http://mibs.snmplabs.com/asn1/IEEE8023-LAG-MIB is out of date

### ISSUE THREAD

**Issue by clarsen** [etingof/pysnmp#338]
file there is updated "201412180000Z".

Later MIB at http://www.ieee802.org/1/files/public/MIBs/IEEE8023-LAG-MIB-201610120000Z.txt is updated "201610120000Z"

Example significant changes that cause validation failures:

```
dot3adAggPortActorSystemPriority OBJECT-TYPE
    SYNTAX       Integer32 (0..255)
    MAX-ACCESS   read-write
    STATUS       current
    DESCRIPTION
        "A 2-octet read-write value used to define the priority
        value associated with the Actor's System ID."
    REFERENCE
        "7.3.2.1.2"
    ::= { dot3adAggPortEntry 2 }
```

vs.
```
dot3adAggPortActorSystemPriority OBJECT-TYPE
    SYNTAX       Integer32 (0..65535)
    MAX-ACCESS   read-write
    STATUS       current
    DESCRIPTION
        "A 2-octet read-write value used to define the priority
        value associated with the Actor's System ID."
    REFERENCE
        "7.3.2.1.2"
    ::= { dot3adAggPortEntry 2 }
```

**Comment by etingof** [comment]
Thank you for the heads up!

I just run the [mibcopy](http://snmplabs.com/pysmi/mibcopy.html) tool against the entire [ieee802](http://www.ieee802.org/1/files/public/MIBs/) repo. The total of 34 MIBs have been copied. So I hope we are now in-sync.

Let me know if else anything comes up!

Thanks!
