### ISSUE TITLE
Set Bulk Command

### ISSUE THREAD

**Issue by saeedghx68** [etingof/pysnmp#34]
Hi, how to set value to multiple oid(more than 10000).
I need Set_Bulk_command.

When is use setCmd, i gave connection time out.

please help me!

**Comment by etingof** [comment]
There is no such thing as SET BULK command defined by the protocol. 

The only optimization I can think of is to partition your OID set onto pieces and stuff as many OID-value pairs into a SET command as your SNMP agent is capable to process. I think it's around few dozens.

**Comment by saeedghx68** [comment]
Okey, tnx
I try use it.
