### ISSUE TITLE
ValueConstraintError with AES encryption

### ISSUE THREAD

**Issue by bharatjosh** [etingof/pysnmp#351]
Hi,

We are using pysnmp 4.4.4 and pycryptodomex 3.72 versions in our application.

We are currently facing following issue when we use AES 128 bit encryption:

ValueConstraintError('<ConstraintsIntersection object at 0x7f22c5455278 consts <ValueSizeConstraint object at 0x7f22cb29c160 consts 0, 65535>, <ValueSizeConstraint object at 0x7f22c5445710 consts 0, 255>, <ValueSizeConstraint object at 0x7f22c5455240 consts 1, 32>> failed at: ValueConstraintError("<ValueSizeConstraint object at 0x7f22c5455240 consts 1, 32> failed at: ValueConstraintError(b\'\',)",) at SnmpAdminString',)>

Now another mystry for me is that the OID we are fetching here is System-name OID (1.3.6.1.2.1.1.5) which is of type 'String' but here it is failing in SnmpAdminString. 

Also, we have tried it with DES, v2c and it seems to work fine. 

I also captured the packet using tcpdump and decrypted it in wireshark using same credentials to check the data and wireshark was able to decrypt it without any issues and showed me the right data.

I also enabled pysnmp debug but couldn't get any more information on identifying what could be going wrong here.

Will really appreciate if anyone has a fix for this or can suggest a workaround.

Also, please let me know if you need any more information.

Regards,
Bharat

**Comment by yellowpattern** [comment]
I'm also seeing this error but I see it no matter what authentication/privacy options I use.


  File "/home/me/lib/python/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 360, in nextCmd
    lookupMib=options.get('lookupMib', True)))
  File "/home/me/lib/python/pysnmp/hlapi/asyncore/cmdgen.py", line 349, in nextCmd
    snmpEngine, authData, transportTarget, contextData.contextName)
  File "/home/me/lib/python/pysnmp/hlapi/lcd.py", line 64, in configure
    privKeyType=authData.privKeyType
  File "/home/me/lib/python/pysnmp/entity/config.py", line 187, in addV3User
    (usmUserEntry.name + (13,) + tblIdx1, 'createAndGo'))
  File "/home/me/lib/python/pysnmp/smi/instrum.py", line 256, in writeVars
    return self.flipFlopFsm(self.fsmWriteVar, varBinds, acInfo)
  File "/home/me/lib/python/pysnmp/smi/instrum.py", line 239, in flipFlopFsm
    raise origExc
pysnmp.smi.error.InconsistentValueError: InconsistentValueError({'msg': 'Row consistency check failed for MibScalarInstance((1, 3, 6, 1, 6, 3, 15, 1, 2, 2, 1, 3, 25, 128, 0, 79, 184, 5, 100, 101, 118, 45, 98, 111, 120, 45, 51, 46, 105, 110, 46, 115, 111, 102, 116, 46, 128, 152, 4, 78, 111, 110, 101), <SnmpAdminString schema object, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint object, consts 0, 255>>, tagSet <TagSet object, tags 0:0:4>, encoding utf-8>)'})

**Comment by bharatjosh** [comment]
We could finally fix this issue.

It happens when either priv_key or auth_key is passed as empty string.

Pl double check your code.

Regards,
Bharat

**Comment by yellowpattern** [comment]
Ah yes, I wasn't passing the username.

**Comment by yellowpattern** [comment]
There are some documentation bugs on the web page:
http://snmplabs.com/pysnmp/examples/hlapi/asyncore/sync/manager/cmdgen/walking-operations.html

In the "Walk Whole MIB", it has 
$ snmpwalk -v3 -lauthPriv -u usr-md5-none -A authkey1 -X privkey1 demo.snmplabs.com IF-MIB::
but the code only sets auth1key.

also, "-u" maps to securityName, not userName.

**Comment by bharatjosh** [comment]
As I mentioned, we were passing empty string for auth_key and/or priv_key. So am closing this issue as it has no issue in pysnmp library.
