### ISSUE TITLE
Missing '

### ISSUE THREAD

**Issue by GilaAquila** [etingof/pysnmp#4]
inside the example code there is a missing '
[https://github.com/etingof/pysnmp/blob/master/README.md]

at the line: 
`if errorStatus:  # SNMP agent errors
        print(##here##%s at %s' % (errorStatus.prettyPrint(), varBinds[int(errorIndex)-1] if errorIndex else '?'))`

thank you

**Comment by etingof** [comment]
Fixed, thanks!
