### ISSUE TITLE
PySNMP needs to pin to a single version of PyASN1

### ISSUE THREAD

**Issue by colinmcintosh** [etingof/pysnmp#41]
Twice in the past month PyASN1 has had a release (0.2.2 and 0.2.3) that has broken PySNMP prior to the latest version. This would not be a problem if the previous versions of PySNMP were compatible with PyASN1. However it seems that the changes to PyASN1 break backwards compatibility even though only the micro version number is incremented.

I believe that PySNMP should be pinned to a single compatible version of PyASN1 to prevent this issue in the future.

**Comment by etingof** [comment]
Yes, I agree. And I'm sorry for the whirlpool of changes to pyasn1 lately (they are for the greater good though!).

I will make a pinned release of pysnmp as you've suggested.

Thank you for the heads up!

**Comment by colinmcintosh** [comment]
Excellent! Thanks for the quick response!

**Comment by etingof** [comment]
Version [4.3.4](https://github.com/etingof/pysnmp/releases/tag/v.4.3.4) has been released on PyPI.
