### ISSUE TITLE
Global context is not accessible through cbCtx

### ISSUE THREAD

**Issue by atolikin94** [etingof/pysnmp#433]
If you pass some global object, e.g., a list, as cbCtx into NotificationRecevier, and then append a value to that list - the list in the global context will remain empty.

**Comment by rowshi** [comment]
The project maintainer (Ilya Etingof) unfortunately passed away on [August 10th, 2022](https://lists.openstack.org/pipermail/openstack-discuss/2022-August/030062.html) and your issue will not be resolved.

There is a fork of the project with a group of maintainers called [pysnmp/pysnmp](https://github.com/pysnmp/pysnmp)

**Comment by lextm** [comment]
@rowshi Sadly the Splunk guys didn't fork it naturally, so their fork does not appear in the network graph,

https://github.com/etingof/pysnmp/network

There are quite a few forks, and I am trying to consolidate the patches to a single one. #429

**Comment by lextm** [comment]
@atolikin94 you will have to provide some sample code for others to reproduce the issue you reported. Then we might see whether it needs a patch or not.

**Comment by atolikin94** [comment]
I found out how to workaround the issue already, so this one can be closed.

RIP Ilya Etingof.
