### ISSUE TITLE
Strange error when running the code given

### ISSUE THREAD

**Issue by Prism-hua** [etingof/pysnmp#452]
Here is the error when I running the code given in the first example:

TypeError: <lambda>() takes 3 positional arguments but 4 were given
caused by <class 'TypeError'>: <lambda>() takes 3 positional arguments but 4 were given

PLease help.

**Comment by lextm** [comment]
Duplicate to recent issues like #438.

**Comment by Prism-hua** [comment]
**@lextm**
Which version of pyasn1 can be downloaded to solve this problem?
Any of 0.4.x?

**Comment by Prism-hua** [comment]
I tried the 0.4.1 release of pysan1, and solved my problem.
thanks.

**Comment by lextm** [comment]
You can close this issue if that solution works for you.
