### ISSUE TITLE
Python 3.12 compatibility - deprecated asyncore

### ISSUE THREAD

**Issue by bauergeorg** [etingof/pysnmp#457]
[asyncore](https://docs.python.org/3.11/library/asyncore.html#module-asyncore) is deprecated since python 3.6. In Python 3.12 it will be removed. You should use: [asyncio](https://docs.python.org/3.11/library/asyncio.html#module-asyncio) instead.

**Comment by lextm** [comment]
You should read #429 which already covered this.

**Comment by bauergeorg** [comment]
Thank you @lextm for your message. I will checkout [LeXtudio ](https://pypi.org/project/pysnmp-lextudio/).
