### ISSUE TITLE
TRAP Reciver in PYSNMP 4.3.4 ;RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by rootsourav** [etingof/pysnmp#46]
The Pysnmp Trap Reciver is crashing with PYSNMP-4.3.4 same with 4.3.3 With 4.3.2 it was working just fine.
with error:
;RuntimeError: maximum recursion depth exceeded while calling a Python object

Iusse is reproducable every time when there is multiple trap message sent from the agent.
Meaning with:
snmptrap -v3 -u user_auth1 -l noAuthNoPriv -e 80000F150000000000000000 127.0.0.1:1036 123 1.3.6.1.6.3.1.1.5.1
Trap message recive and decode happnes just fine.

Test Platform: Red Hat Enterprise Linux Server release 6.8
Python: 2.7.8
PIP LIST:
[pip.txt](https://github.com/etingof/pysnmp/files/849072/pip.txt)

Refer error.txt for the error details.
[error.txt](https://github.com/etingof/pysnmp/files/849020/error.txt)

for used code please refer:
[trap_.txt](https://github.com/etingof/pysnmp/files/849025/trap_.txt)

**Comment by etingof** [comment]
So far I can't easily reproduce this issue (still keep on trying). I guess you send some other OIDs along with snmptrap command., do you?

Which MIBs you load in your script?

Thanks!

**Comment by rootsourav** [comment]
Yes from my real HW I am sending some more TRAP to the reciver, I am attaching the debug log of the same trap with PYSNMP 4.3.2 and PYSNMP 4.3.4.
[pysnmp4.3.2_debug_log.txt](https://github.com/etingof/pysnmp/files/852706/pysnmp4.3.2_debug_log.txt)
[pysnmp_4.3.4_debug_log.txt](https://github.com/etingof/pysnmp/files/852707/pysnmp_4.3.4_debug_log.txt)

with cold start oid(snmptrap -v3 -u user_auth1 -l noAuthNoPriv -e 80000F150000000000000000 127.0.0.1:1036 123 1.3.6.1.6.3.1.1.5.1) the issue is will not be reproduced.

**Comment by etingof** [comment]
Thank you for the detailed logs, that is helpful!

Where could I get these MIBs: FSS-COMMON-TC,FSS-COMMON-LOG,XYZ-COMMON-SMI,XYZNMS? Are they publicly available somewhere?

Have you tried [my fix](https://github.com/etingof/pysnmp/tree/textual-convention-recursion-fix) already?

**Comment by rootsourav** [comment]
Hi I have tried your fix and seems its working fine with the fix. Please find the attached new log.
you can reach me at twiter @rootsourav and skype Skype Name: bhattacharya.sourav


[pysnmp-4.3.5_debug_log.txt](https://github.com/etingof/pysnmp/files/852772/pysnmp-4.3.5_debug_log.txt)

I can give the MIB files info in public post; please let me know your email id I will send you the same.
I our origniztion your snmp solution is used in large scale so any change or failure get picked up very very soon.

**Comment by etingof** [comment]
Good to know my fix helped! I am going to merge it and make a pysnmp release soon.

My e-mail is etingof@gmail.com. Thank you!

**Comment by rootsourav** [comment]
Can you please give me an estimateed date of the 4.3.5 release.

**Comment by etingof** [comment]
I'm planning to make a release till the end of this week.

**Comment by jccardonar** [comment]
I was suffering the same problem, and can confirm that the changes fixed it.

The impacted MIB was this one: https://github.com/pgmillon/observium/blob/master/mibs/aos/TIMETRA-FILTER-MIB

However, the TIMETRA MIBs have a handful of issues related to defval validation, so it might not be the best MIB for testing.

**Comment by etingof** [comment]
@jccardonar Thank you for the feedback! The new release is on its way! ;-)

MIBs are generally rather buggy. We have a workaround which is to fix broken MIBs manually and keeping the compiled versions at http://mibs.snmplabs.com/ where pysnmp could find them automatically.

If you think TIMETRA-FILTER-MIB issues could be automatically worked around by the compiler, you are welcome to raise an issue for pysmi (send a PR). ;-)

**Comment by jccardonar** [comment]
@etingof  Thank you for the great library!

Ehh, I am thinking about it. These TIMETRA MIBs have around 20 objects with default values violating their syntax. For my use case, which is basically MIB navigation, I could turn the verification process off, maybe by catching exceptions in verifySubtypeSpec and defaulting to Novalue or something. However,  for broader use cases, it is probably better to keep it like that.

**Comment by etingof** [comment]
4.3.5 is out!

**Comment by rootsourav** [comment]
Great! Thanks a lot.
