### ISSUE TITLE
snmp v3 authpriv set  error  with  No SNMP response received before timeout ()

### ISSUE THREAD

**Issue by code164** [etingof/pysnmp#461]
[snmpv3set.zip](https://github.com/user-attachments/files/16466804/snmpv3set.zip)

 #------------------------------------------------------------------------------
from pysnmp.hlapi import *
import sys
SYSNAME = '1.3.6.1.2.1.1.5.0'
hostname = 'testv33'
hostname1 = 'testv3'
def show_item( ):

    g = getCmd(SnmpEngine()
               , CommunityData('testv2', mpModel=1)
               , UdpTransportTarget(('172.17.126.76', 161))
               , ContextData()
               , ObjectType(ObjectIdentity(SYSNAME))
               , lookupMib=True)
    errorIndication, errorStatus, errorIndex, varBinds = next(g)

    for varBind in varBinds:
            print(' = '.join([x.prettyPrint() for x in varBind]))

#Show initial value
show_item()
#Setting new value
def set_item(hostname):
    g = setCmd(SnmpEngine()
           , UsmUserData("testv3"
                         , authProtocol=usmHMACMD5AuthProtocol
                         , authKey="test123456"
                         , privProtocol=usmAesCfb128Protocol
                         , privKey="test123456" )
           , UdpTransportTarget(('[172.17.126.76](http://172.17.126.76/)', 161))
           , ContextData()
           , ObjectType(ObjectIdentity(SYSNAME), hostname)
           , lookupMib=False)
    errorIndication, errorStatus, errorIndex, varBinds = next(g)

    print(errorIndication, varBinds)
    if errorIndication:
         print("exit this script !!!")
         sys.exit()

    for oid, val in varBinds:
         print(oid.prettyPrint(), val.prettyPrint())
set_item(hostname)
show_item()
set_item(hostname1)
show_item()
 #------------------------------------------------------------------------------------

env
`Package            Version
------------------ --------
bcrypt             4.1.3
certifi            2024.7.4
cffi               1.16.0
charset-normalizer 3.3.2
cryptography       42.0.8
idna               3.7
infrastructure     3.5.6
Jinja2             3.1.4
MarkupSafe         2.1.5
paramiko           2.7.1
pip                24.1
ply                3.11
pyasn1             0.6.0
pycparser          2.22
pycryptodomex      3.20.0
PyNaCl             1.5.0
pysmi              1.4.4
pysnmp             4.4.12
requests           2.32.3
setuptools         70.1.0
sshtunnel          0.1.5
urllib3            2.2.2
wheel              0.43.0`

missing EngineID  boots 0 Time 0
![image](https://github.com/user-attachments/assets/4299207c-3164-4cbf-8d98-8ec42667da0b)
reply including EngineID  boots  Time 
![image](https://github.com/user-attachments/assets/4790406f-7a49-40e0-ad07-b2e5e317178e)
respond only with EngineID  and boots  Time still 0
![image](https://github.com/user-attachments/assets/c483bfe3-cfd4-4c10-8d02-9b0d36e5e318)

Maybe there is something wrong

**Comment by lextm** [comment]
Please study #429 to learn more.

Release 4.4.x is known to have many bugs in SNMP v3 support, so you need to upgrade to release 6.x.

**Comment by code164** [comment]
> Please study #429 to learn more.
> 
> Release 4.4.x is known to have many bugs in SNMP v3 support, so you need to upgrade to release 6.x.

oh sorry
and you are right, when i changed to 6.2.4 ,it works!!

------------------------------------------------------------
(pysnmp) Debian:~$ python hlapiasync.py
None 0 0 [ObjectType(ObjectIdentity(<ObjectName value object, tagSet <TagSet object, tags 0:0:6>, payload [1.3.6.1.2.1.1.5.0]>), <DisplayString value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint object, consts 0, 255>, <ValueSizeConstraint object, consts 0, 255>>, encoding iso-8859-1, payload [testv3]>)]
(pysnmp) Debian:~$
(pysnmp) Debian:~$
(pysnmp) Debian:~$ pip list
Package            Version
------------------ --------
certifi            2024.7.4
cffi               1.16.0
charset-normalizer 3.3.2
cryptography       43.0.0
idna               3.7
Jinja2             3.1.4
MarkupSafe         2.1.5
pip                24.1
ply                3.11
pyasn1             0.6.0
pycparser          2.22
pysmi              1.4.4
pysnmp             6.2.4
pysnmpcrypto       0.0.4
requests           2.32.3
setuptools         70.1.0
urllib3            2.2.2
wheel              0.43.0
(pysnmp) Debian:~$cat hlapiasync.py
import asyncio
from pysnmp.hlapi.asyncio import *
SYSNAME = '1.3.6.1.2.1.1.5.0'
name = 'testv3'

async def run(hostname):
    errorIndication, errorStatus, errorIndex, varBinds = await setCmd(
       SnmpEngine(),
       UsmUserData("testv3"
                         , authProtocol=usmHMACMD5AuthProtocol
                         , authKey="test123456"
                         , privProtocol=usmAesCfb128Protocol
                         , privKey="test123456" ),
       UdpTransportTarget(('172.17.126.76', 161)),
       ContextData(),
       ObjectType(ObjectIdentity(SYSNAME), hostname)
    )
    print(errorIndication, errorStatus, errorIndex, varBinds)

asyncio.run(run(name))
