### ISSUE TITLE
Error in doc

### ISSUE THREAD

**Issue by cmarmonier** [etingof/pysnmp#465]
Code exemple in documentation is wrong for getCmd : https://pysnmp.readthedocs.io/en/latest/quick-start.html

It should be :
`from pysnmp.hlapi import *

data = (
    ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysLocation', 0)),
    ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysDescr', 0)),
)

iterator = getCmd(
    SnmpEngine(),
    CommunityData('public', mpModel=0),
    UdpTransportTarget(('demo.snmplabs.com', 161)),
    ContextData(),
    *data
)

#errorIndication, errorStatus, errorIndex, varBinds = next(iterator) # wrong doc
errorIndication, errorStatus, errorIndex, varBinds = iterator # fix

if errorIndication:
    print(errorIndication)

elif errorStatus:
    print('%s at %s' % (errorStatus.prettyPrint(),
                        errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))

else:
    for varBind in varBinds:
        print(' = '.join([x.prettyPrint() for x in varBind]))
`

**Comment by lextm** [comment]
That's the wrong place to learn this project. Please use https://pysnmp.com

Read #429 to learn more.

**Comment by cmarmonier** [comment]
Ok, I close this thread
