### ISSUE TITLE
Missing top.html for building doc

### ISSUE THREAD

**Issue by radaiming** [etingof/pysnmp#5]
Hi, 

I could not make html doc, looks it's because of missing top.html, this issue happens in 4.3.1 and 4.3.2, also in current git repo:

~~~~~~~~
Exception occurred:
  File "/usr/lib64/python2.7/site-packages/sphinx/jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: top.html
~~~~~~~~

**Comment by etingof** [comment]
Hopefully, fixed in master. Please, try and report back in case of issues.

**Comment by radaiming** [comment]
Seems I can also apply b0d77a9 to 4.3.1 and 4.3.2, I tried and all master/4.3.1/4.3.2 looks OK, thanks.
