### ISSUE TITLE
Problems forming instance-identifier  for TCP-MIB::tcpConnectionState

### ISSUE THREAD

**Issue by jccardonar** [etingof/pysnmp#54]
Hello,

I am getting a different Instance identifier for TCP-MIB::tcpConnectionState  than the one in the documentation (http://pysnmp.sourceforge.net/docs/pysnmp-hlapi-tutorial.html). I wonder if this is a problem with my local MIB or maybe a library problem.

~~~~
from pysnmp.hlapi import ObjectIdentity
from pysnmp.smi import builder, view
mibBuilder = builder.MibBuilder()
mibViewController = view.MibViewController(mibBuilder)
x = ObjectIdentity('TCP-MIB', 'tcpConnectionState','ipv4', '195.218.254.105', 41511,'ipv4', '194.67.1.250', 993)
x.resolveWithMib(mibViewController)
~~~~

After running x.getOid(), I get:

1.3.6.1.2.1.6.19.1.7.1.15.49.57.53.46.50.49.56.46.50.53.52.46.49.48.53.41511.1.12.49.57.52.46.54.55.46.49.46.50.53.48.993

To create the instances, Pysnmp is taking the IPs as variable-length strings instead of IPv4. The resulting OIDs will not function against a device, and I am not sure how to handle these situations.

I apologise if this is not a bug, but I got zero responses after posting this in the user list.

**Comment by etingof** [comment]
Thank you for rising this issue!

To which part of pysnmp documentation you are referring to here?

What you observe seems to be a bug in pysmi and missing feature in pysnmp. There was a problem with pysmi's pysnmp files generation backend which was fixed, so I'd advise you to remove caches in `~/.pysnmp/mibs/*` and `~/.pysnmp/mibs/*/*`, then install pysmi from [master](https://github.com/etingof/pysmi).

That should fix `DISPLAY-HINT` generation at pysnmp MIB files. But I think there is another issue -- pysnmp is not able to cast `InetAddress` into `InetAddressIPv4` based on `InetAddressType` value (`ipv4` in your case) so it always treats IP addresses as `InetAddress` which is a raw string. I'm going to address this with pysnmp shortly and report back here.

Interestingly, Net-SNMP's `snmptranslate` seems to behave the same:

```
$ snmptranslate 1.3.6.1.2.1.6.19.1.7.1.15.49.57.53.46.50.49.56.46.50.53.52.46.49.48.53.41511.1.12.49.57.52.46.54.55.46.49.46.50.53.48.993
TCP-MIB::tcpConnectionState.ipv4."195.218.254.105".41511.ipv4."194.67.1.250".993
$ snmptranslate -On TCP-MIB::tcpConnectionState.ipv4.\"195.218.254.105\".41511.ipv4.\"194.67.1.250\".993
.1.3.6.1.2.1.6.19.1.7.1.15.49.57.53.46.50.49.56.46.50.53.52.46.49.48.53.41511.1.12.49.57.52.46.54.55.46.49.46.50.53.48.993
```
I still do not think the above OID is correctly encoded, is it?

**Comment by jccardonar** [comment]
Thanks a lot for the answer! 

The example is in the section "Working with SNMP tables" from pysnmp-hlapi-tutorial.html, just after 

> "PySNMP's :py:class:`~pysnmp.smi.rfc1902.ObjectIdentity` class takes any number of indices in human-friendly representation and converts them into full OID". 

It is interesting to know that net-snmp does the same. I would say this is not the right encoding since the IP addresses  should resemble their HEX values. Empirically, this matches what I get from devices (at least the ones I normally work with). For instance:

`.1.3.6.1.2.1.6.19.1.7.1.4.10.0.1.4.179.1.4.10.0.1.2.11508 = INTEGER: established(5)
.1.3.6.1.2.1.6.19.1.7.1.4.10.0.1.4.646.1.4.10.0.1.5.26966 = INTEGER: established(5)
.1.3.6.1.2.1.6.19.1.7.1.4.10.0.1.4.646.1.4.10.0.1.6.11769 = INTEGER: established(5)
.1.3.6.1.2.1.6.19.1.7.1.4.10.0.1.4.43261.1.4.10.0.1.3.646 = INTEGER: established(5)`

So, if i try `snmpwalk  -m all -v2c -cpublic 10.0.0.4 TCP-MIB::tcpConnectionState.ipv4.\"10.0.1.4\"`, the query indeed fails. In other words, the value of the IP should be 0x0A000104, which is not the result of parsing the IP literally as a string. Maybe IPs should not be entered as strings at all...

By the way, why is a IPv4 encoded as 4.10.0.1.4, instead of just 10.0.1.4 knowing that  InetAddressIPv4 has a fix size of 4, and rfc2578 states that N fix-length variables should just have N sub-identifiers?

**Comment by etingof** [comment]
Just a quick update:

> There was a problem with pysmi's pysnmp files generation backend which was fixed, so I'd 
> advise you to remove caches in ~/.pysnmp/mibs/* and ~/.pysnmp/mibs/*/*, then install pysmi
> from master.

This fix made its way into the latest pysmi [release](https://github.com/etingof/pysmi/releases/tag/v0.1.2).

> By the way, why is a IPv4 encoded as 4.10.0.1.4, instead of just 10.0.1.4 knowing that 
> InetAddressIPv4 has a fix size of 4, and rfc2578 states that N fix-length variables should 
> just have N sub-identifiers?

That's because pysnmp does not realize that the type is `InetAdddressIPv4` (which is a fixed-length string), instead it treats it as `InetAddress` (which is a variable-length string). This needs to be implemented and I'm on it.

**Comment by etingof** [comment]
I think I've implemented the missing feature to pysnmp & pysmi. If you take both from GitHub master, you should be able to en/decode `InetAddress`-based objects in indices properly.

**Comment by jccardonar** [comment]
Thanks for the quick response of this again!
I tried the code, and the results is as you confirmed:
```
from pysnmp.hlapi import ObjectIdentity
from pysnmp.smi import builder, view
mibBuilder = builder.MibBuilder()
mibViewController = view.MibViewController(mibBuilder)
x = ObjectIdentity('TCP-MIB', 'tcpConnectionState','ipv4', '195.218.254.105', 41511,'ipv4', '194.67.1.250', 993)
x.resolveWithMib(mibViewController)

In [2]: x.getOid()
Out[2]: ObjectName('1.3.6.1.2.1.6.19.1.7.1.195.218.254.105.41511.1.194.67.1.250.993')
```

Here comes my confusion, which is related to the last question of my latest comment. If I walk the 1.3.6.1.2.1.6.19.1.7. on a router, this is what I get:

```
snmpwalk -v2c -cpublic 10.0.0.4  1.3.6.1.2.1.6.19.1.7 -On
.1.3.6.1.2.1.6.19.1.7.1.4.10.0.1.4.179.1.4.10.0.1.2.11508 = INTEGER: established(5)
.1.3.6.1.2.1.6.19.1.7.1.4.10.0.1.4.646.1.4.10.0.1.5.26966 = INTEGER: established(5)
.1.3.6.1.2.1.6.19.1.7.1.4.10.0.1.4.646.1.4.10.0.1.6.11769 = INTEGER: established(5)
.1.3.6.1.2.1.6.19.1.7.1.4.10.0.1.4.43261.1.4.10.0.1.3.646 = INTEGER: established(5)
```

As you can see, the router encodes the IP as a variable object string instead of the fix size that the IP should be... Probably the router does use InetAddress (I don't know how to test that).  INET-ADDRESS-MIB.txt seems to confirm that the current pysmi/pysnmp way is the correct one, but the fact that the routers return it differently confuses me.

**Comment by etingof** [comment]
> As you can see, the router encodes the IP as a variable object string instead of the fix size 
> that the IP should be...

Looks like it's a [special case](https://tools.ietf.org/html/rfc4001#section-4.1):

```
Instance sub-identifiers are then of the form T.N.O1.O2...On, where T is the value of the InetAddressType object, O1...On are the octets in the InetAddress object, and N is
the number of those octets.
```

I'm going to change pysnmp en/decoder accordingly.

**Comment by etingof** [comment]
> I'm going to change pysnmp en/decoder accordingly.

Fixed. Please let me know in case of further troubles.

**Comment by jccardonar** [comment]
Great find! It indeed works. Thanks @etingof, learned a lot from this case!
