### ISSUE TITLE
Pysnmp Import error with PYSNMP 4.3.6

### ISSUE THREAD

**Issue by rootsourav** [etingof/pysnmp#60]
Hi,
With PYSNMP 4.3.6-- I am observing a new issue:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Python 2.7.8 (default, Dec  4 2014, 15:24:39)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysnmp
>>> from pysnmp.entity.rfc3413.oneliner import  ntforg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/VIRT/lib/python2.7/site-packages/pysnmp/entity/rfc3413/oneliner/ntforg.py", line 1, in <module>
    pysnmp/carrier/asyncore/dgram/base.py#
NameError: name 'pysnmp' is not defined
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Reason is in ntforg.py the 1st line creating this problem.

$ cat ntforg.py|head
**pysnmp/carrier/asyncore/dgram/base.py#**

------------------------------------------------------------------------------------------------------

The issue was not observed in 4.3.5.

**Comment by etingof** [comment]
Oh... I really need to understand how that slipped in besides all the tests...

Fixed in master! Can you please try it out and let me know if it works for you. I will make a release shortly afterwards.

Thank you!

**Comment by rootsourav** [comment]
@etingof Tested in master and everything seems find now. Please give me a tentative date of next release.

Thanks a lot.

**Comment by etingof** [comment]
Just released 4.3.7 at [GitHub](https://github.com/etingof/pysnmp/releases/tag/v4.3.7) and PyPI.

Thanks for the heads up!
