### ISSUE TITLE
build-pysnmp-mib

### ISSUE THREAD

**Issue by glaslos** [etingof/pysnmp#61]
What happened to that script and where can I find it? I use it to import mib files into pysnmp

**Comment by etingof** [comment]
The script (along with the `smidump` tool it relies on) is superseded by the pure-python [pysmi](https://github.com/etingof/pysmi) MIB compiler.

If you upgrade to a reasonably resent pysnmp, it will pull in the pysmi as a dependency and call it behind the scenes to resolve MIB names. That should work fully automatically so you might not need manual MIB compilation anymore.

But you can still turn any MIB into pysnmp module by hand with the `mibdump.py` tool which is shipped along with `pysmi`. Just `pip install pysmi` and run [mibdump.py](http://pysmi.sourceforge.net/user-perspective.html).

**Comment by glaslos** [comment]
Thanks for the quick feedback. Here is what we used to do: https://github.com/mushorg/conpot/blob/master/conpot/protocols/snmp/build_pysnmp_mib_wrapper.py I will see how we can change that to use the new features.

**Comment by etingof** [comment]
So if your goal is to just compile MIBs  (and dependencies) into pysnmp, take a look [at this example](https://github.com/etingof/pysmi/blob/master/examples/download-and-compile-smistar-mibs-into-pysnmp-files.py). It should fully replace the libsmi-based approach plus it might work way more reliable and accurate plus it could pull ASN.1 MIBs from multiple locations, including HTTP/FTP servers.

There is also [some documentation](http://pysmi.sourceforge.net/developer-documentation.html) on the package.
