### ISSUE TITLE
Could Not able To load "IF-MIB" using loadModules

### ISSUE THREAD

**Issue by sbhattach** [etingof/pysnmp#63]
Hi 

I am having problem to load "IF-MIB" using loadModules.
Using PYSNMP-4.3.8.

after I call mibBuilder.loadModules('IF-MIB') its just hangs there.
Debug log attached.
Reproducible: Yes.
[snmp_debug_log.txt](https://github.com/etingof/pysnmp/files/1125037/snmp_debug_log.txt)

```
>>> from pysnmp.smi import builder, view, compiler, rfc1902, error
>>> custom_mib_paths = "/usr/share/snmp/mibs/"
>>> mibBuilder = builder.MibBuilder()
>>> compiler.addMibCompiler(mibBuilder, sources=custom_mib_paths)
>>> from pysnmp import debug
>>> debug.setLogger(debug.Debug('all'))
2017-07-05 09:06:01,505 pysnmp: running pysnmp version 4.3.8
2017-07-05 09:06:01,506 pysnmp: debug category 'all' enabled
>>> mibViewController = view.MibViewController(mibBuilder)
>>> mibBuilder.loadModules('IF-MIB')
```

**Comment by sbhattach** [comment]
Please close this case its because the dependency MIB IANAifType-MIB was missing. My bad.

**Comment by etingof** [comment]
I guess you should have enable the pysmi debugger to see why MIB load hangs. 

Anyway, good to know you resolved this!
