### ISSUE TITLE
ignoreNonIncreasingOid not working?

### ISSUE THREAD

**Issue by AZF-EDV-Team** [etingof/pysnmp#65]
found this Link: http://pysnmp.sourceforge.net/faq/oids-not-increasing.html
tried to use cmdGen.ignoreNonIncreasingOid = True but the error remains: OIDs not increasing. With snmpwalk and -Cc its working like expected.

Sth i missed?

---------------
code:
from pysnmp.entity.rfc3413.oneliner import cmdgen

cmdGen = cmdgen.CommandGenerator()
cmdGen.ignoreNonIncreasingOid = True   # doesnt matter if present or not!
errorIndication, errorStatus, errorIndex, varBindTable = cmdGen.nextCmd(
cmdgen.CommunityData('public'),
cmdgen.UdpTransportTarget(("MyIP", MyPort)),
'1.3.6.1.2.1.17.7.1.2.2.1.2',
)

if errorIndication:
    print(errorIndication)
else:
    if errorStatus:
        print('%s at %s' % (
            errorStatus.prettyPrint(),
            errorIndex and varBindTable[-1][int(errorIndex)-1] or '?'
            )
        )
    else:
        for varBindTableRow in varBindTable:
        	for name, val in varBindTableRow:
        		print('%s = %s' % (name.prettyPrint(), val.prettyPrint()))

**Comment by etingof** [comment]
Thank you for rising this issue!

The `.ignoreNonIncreasingOid` class attribute has been [refactored](https://github.com/etingof/pysnmp/blob/master/CHANGES.txt#L515) into keyword arguments long ago. I've just updated the [documentation](https://github.com/etingof/pysnmp/blob/master/docs/source/faq/oids-not-increasing.rst) to reflect this.

As a side note, I'd advice you to migrate to the [hlapi API](http://pysnmp.sourceforge.net/examples/hlapi/asyncore/sync/manager/cmdgen/table-operations.html#fetch-whole-snmp-table) as it's more efficient and better supported.

**Comment by AZF-EDV-Team** [comment]
Thanks for the answer, it solved my Problem! 
I missed the refactoring, sorry for that. 

At the moment i stay at the old API but it going to be an TODO to migrate to the hlapi API.

**Comment by Wangjunling1** [comment]
I have a problem, too
