### ISSUE TITLE
SNMP OID sysUpTime is missing one digit?

### ISSUE THREAD

**Issue by perskes** [etingof/pysnmp#68]
Hey, I encountered a problem parsing the return value of the sysUpTime request via SNMPv2 on out Fortinet and HP Equipment. 

There is simply a digit missing when it comes to this request.
It returns 227821100 which is around 2.6 days!
When I multiple the number *10 and run it though my time-parser, it gives me the correct ~26 days.

It might be my code, but I didn't find the issue there, so I thought I'll open an issue.
```

def getSNMP(community, host, OID):
    iterator = getCmd(SnmpEngine(),
                      CommunityData(community),
                      UdpTransportTarget((host, 161)),
                      ContextData(),
                      ObjectType(ObjectIdentity('SNMPv2-MIB', OID, 0)))

    errorIndication, errorStatus, errorIndex, varBinds = next(iterator)

    if errorIndication:  # SNMP engine errors
        print(errorIndication)
    else:
        if errorStatus:  # SNMP agent errors
            print('%s at %s' % (errorStatus.prettyPrint(), varBinds[int(errorIndex)-1] if errorIndex else '?'))
        else:
            for varBind in varBinds:  # SNMP response contents
                #print(' = '.join([x.prettyPrint() for x in varBind]))
                return str(varBind).split("=",1)[-1].strip()
```

This is mostly the code you posted here on github, with a return instead of a print.

Here is my testing code:

```
    if (attribute == "uptime"):
        oid = 'sysUpTime'
        ms = int(getSNMP('public', host, oid))*10
        print(msToReadable(ms))
```

This already gived me the time with a missing digit, unless I add *10 at the end.

And here I'e got the conversion code.
```
def msToReadable(ms):
    x = ms / 1000
    seconds = x % 60
    x /= 60
    minutes = x % 60
    x /= 60
    hours = x % 24
    x /= 24
    days = x

    return str(days).split(".")[0] +  " days, " + str(hours).split(".")[0] + " hours, " + str(minutes).split(".")[0] + " minutes, " + str(seconds).split(".")[0] +" seconds" + ", or " + str(ms) + " ms"


```

It's not really clean, since I just wanted to test a few things, but I hope you can read through it without any problems!

**Comment by etingof** [comment]
The [sysUpTime.0](https://stackoverflow.com/questions/10585321/sysuptime-in-snmp) object is supposed to express system uptime in 1/100 units.  Your code seems to treat it as being expressed in milliseconds which gives you ten times lesser value than it actually is.

Does that explain it?

BTW, this has nothing to do with pysnmp -- the sysUpTime value comes directly from the SNMP agent you query.
