### ISSUE TITLE
Permanently storing custom MIBs

### ISSUE THREAD

**Issue by chendrix4** [etingof/pysnmp#70]
I have been working with pySNMP for a little bit and was just successful in reaching an agent that runs a custom MIB. I have to work with several different systems that each run a custom MIB, and before I begin I want to confirm my thinking. It looks like if I load a MIB once, pySNMP stores it permanently. Is this correct?

For clarification, I originally had to perform a getCmd to get the name of an agent where my varBinds parameter was `ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysDescr', 0)).addAsn1MibSource(file_path)`
Now, I only have to input `ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysDescr', 0))` to achieve the same result.

If I am correct, how does pySNMP know the correct directory from which to read imported MIB? If not, how does pySNMP know how to access an agent?

**Comment by etingof** [comment]
>  It looks like if I load a MIB once, pySNMP stores it permanently. Is this correct?

The pysnmp library asks `pysmi` library to compile original ASN.1 MIBs into a set of Python classes and caches these Pythonized MIBs in [`~/.pysnmp/mibs/`](https://github.com/etingof/pysnmp/blob/master/pysnmp/smi/compiler.py#L12) (on UNIX). This phase only runs if the caller is asking for a MIB which is not yet cached. You can remove this cache at any moment by hand.

>  I originally had to perform a getCmd to get the name of an agent where my varBinds parameter was ....

Yes, that's MIB cache at work.

> If I am correct, how does pySNMP know the correct directory from which to read imported MIB? If  not, how does pySNMP know how to access an agent?

Yes, and you can change the default cache directory by passing `destination='/your/dir` kwargs to [.addAsn1MibSource](http://pysnmp.sourceforge.net/docs/api-reference.html#pysnmp.smi.rfc1902.ObjectIdentity.addAsn1MibSource).

**Comment by etingof** [comment]
I assume this answers your question. Please, reopen this issue if anything remains not clear. ;-)

**Comment by chendrix4** [comment]
Thank you for your response. It does help very much. The weekend threw me or I would have replied sooner.
