### ISSUE TITLE
Running into a loop till timeout in one particular OID

### ISSUE THREAD

**Issue by prauscher** [etingof/pysnmp#76]
Hello,

to be honest, I'm not entirely sure if this is a problem with pysnmp, but using snmpwalk i got no problem. Here is the thing: I updated my server to Debian 9 today, and right after the upgrade, a python-script of mine using PySNMP stopped working:
```
#!/usr/bin/env python3

from pysnmp.entity.rfc3413.oneliner import cmdgen

#root_oid = (1, 3, 6, 1, 4, 1, 2021, 4)
root_oid = (1, 3, 6, 1, 4, 1, 2021, 10)

authentication = cmdgen.CommunityData("public")
transport = cmdgen.UdpTransportTarget(("172.22.120.3", 161))

errorIndication, errorStatus, errorIndex, varBinds = cmdgen.CommandGenerator().nextCmd(authentication, transport, root_oid)

if errorIndication:
    raise Exception(errorIndication)
if errorStatus:
    raise Exception(errorStatus.prettyPrint())

for varBind in varBinds:
    oid, value = varBind[0]
    print(oid)
```
The result of this code will be a `Exception: No SNMP response received before timeout`. By the way, the remote side is a small router with OpenWRT / Lede. Interestingly, if I use the other oid, the code works like a charm. Investigating this using tcpdump lead me to the following:
```
# tcpdump -n -i tun.howard -vvv -xxx port 161 and host 172.22.120.3
tcpdump: listening on tun.howard, link-type RAW (Raw IP), capture size 262144 bytes

21:44:43.440425 IP (tos 0x0, ttl 64, id 33925, offset 0, flags [DF], proto UDP (17), length 70)
    172.22.120.2.37353 > 172.22.120.3.161: [udp sum ok]  { SNMPv2c { GetNextRequest(27) R=6086998  .1.3.6.1.4.1.2021.10 } } 
	0x0000:  4500 0046 8485 4000 4011 6def ac16 7802
	0x0010:  ac16 7803 91e9 00a1 0032 a544 3028 0201
	0x0020:  0104 0670 7562 6c69 63a1 1b02 035c e156
	0x0030:  0201 0002 0100 300e 300c 0608 2b06 0104
	0x0040:  018f 650a 0500
[...]
21:44:43.860167 IP (tos 0x0, ttl 64, id 40912, offset 0, flags [DF], proto UDP (17), length 74)
    172.22.120.3.161 > 172.22.120.2.37353: [udp sum ok]  { SNMPv2c { GetResponse(31) R=6087012  .1.3.6.1.4.1.2021.10.1.5.3=4 } } 
	0x0000:  4500 004a 9fd0 4000 4011 52a0 ac16 7803
	0x0010:  ac16 7802 00a1 91e9 0036 a113 302c 0201
	0x0020:  0104 0670 7562 6c69 63a2 1f02 035c e164
	0x0030:  0201 0002 0100 3012 3010 060b 2b06 0104
	0x0040:  018f 650a 0105 0302 0104
21:44:43.862902 IP (tos 0x0, ttl 64, id 33981, offset 0, flags [DF], proto UDP (17), length 73)
    172.22.120.2.37353 > 172.22.120.3.161: [udp sum ok]  { SNMPv2c { GetNextRequest(30) R=6087013  .1.3.6.1.4.1.2021.10.1.5.3 } } 
	0x0000:  4500 0049 84bd 4000 4011 6db4 ac16 7802
	0x0010:  ac16 7803 91e9 00a1 0035 a319 302b 0201
	0x0020:  0104 0670 7562 6c69 63a1 1e02 035c e165
	0x0030:  0201 0002 0100 3011 300f 060b 2b06 0104
	0x0040:  018f 650a 0105 0305 00
21:44:43.887928 IP (tos 0x0, ttl 64, id 40913, offset 0, flags [DF], proto UDP (17), length 75)
    172.22.120.3.161 > 172.22.120.2.37353: [udp sum ok]  { SNMPv2c { GetResponse(32) R=6087013  .1.3.6.1.4.1.2021.11.50.0=9059412 } } 
	0x0000:  4500 004b 9fd1 4000 4011 529e ac16 7803
	0x0010:  ac16 7802 00a1 91e9 0037 53d8 302d 0201
	0x0020:  0104 0670 7562 6c69 63a2 2002 035c e165
	0x0030:  0201 0002 0100 3013 3011 060a 2b06 0104
	0x0040:  018f 650b 3200 4103 8a3c 54
21:44:44.891605 IP (tos 0x0, ttl 64, id 34112, offset 0, flags [DF], proto UDP (17), length 73)
    172.22.120.2.37353 > 172.22.120.3.161: [udp sum ok]  { SNMPv2c { GetNextRequest(30) R=6087014  .1.3.6.1.4.1.2021.10.1.5.3 } } 
	0x0000:  4500 0049 8540 4000 4011 6d31 ac16 7802
	0x0010:  ac16 7803 91e9 00a1 0035 a318 302b 0201
	0x0020:  0104 0670 7562 6c69 63a1 1e02 035c e166
	0x0030:  0201 0002 0100 3011 300f 060b 2b06 0104
	0x0040:  018f 650a 0105 0305 00
```
So, instead of finishing the command after it receives a OID outside of the scope, it just retries. Due to the timing I assume the code never registers the arrival of the last GetResponse altrough every other GetResponse played out quite fine.

As said, I can't assure you the issue is with PySNMP, but using snmpwalk I get correct replies:
```
# snmpwalk -v 2c -c public 172.22.120.3 "1.3.6.1.4.1.2021.10"
iso.3.6.1.4.1.2021.10.1.1.1 = INTEGER: 1
iso.3.6.1.4.1.2021.10.1.1.2 = INTEGER: 2
iso.3.6.1.4.1.2021.10.1.1.3 = INTEGER: 3
iso.3.6.1.4.1.2021.10.1.2.1 = STRING: "Load-1"
iso.3.6.1.4.1.2021.10.1.2.2 = STRING: "Load-5"
iso.3.6.1.4.1.2021.10.1.2.3 = STRING: "Load-15"
iso.3.6.1.4.1.2021.10.1.3.1 = STRING: "0.11"
iso.3.6.1.4.1.2021.10.1.3.2 = STRING: "0.11"
iso.3.6.1.4.1.2021.10.1.3.3 = STRING: "0.08"
iso.3.6.1.4.1.2021.10.1.4.1 = STRING: "1"
iso.3.6.1.4.1.2021.10.1.4.2 = STRING: "5"
iso.3.6.1.4.1.2021.10.1.4.3 = STRING: "15"
iso.3.6.1.4.1.2021.10.1.5.1 = INTEGER: 11
iso.3.6.1.4.1.2021.10.1.5.2 = INTEGER: 11
iso.3.6.1.4.1.2021.10.1.5.3 = INTEGER: 8
```

**Comment by etingof** [comment]
I can't reproduce this behaviour locally. Could you please enable pysnmp debugging:

    from pysnmp import debug
    debug.setLogger(debug.Debug('io', 'msgproc', 'secmod', 'dsp'))

...and share the output? The clue must be there...

**Comment by prauscher** [comment]
After doing some calculations, I get an idea of what might be the issue here: The snmpd sends a Counter32-Value of length 3 (0x8ba43c). Like snmpwalk, PySNMP prefixes this to 0xff8ba43c. The issue with PySNMP now is, that it interprets this as a negative number, -7625668, not as a positive number which would be 4287341628 (and therefore perfectly fit in the ValueRangeConstraint).
Sadly, I do not know the code of PySNMP good enough to provide a fix, but maybe this is a help aswell.

**Comment by etingof** [comment]
Thank you for your research!

I will take a look [at the code](https://github.com/etingof/pyasn1/blob/master/pyasn1/codec/ber/decoder.py#L95) to see where the bug is.

**Comment by prauscher** [comment]
Mhh, fixing this does not look as easy as thought. In theory, one must simply set `signed = False` in [L102](https://github.com/etingof/pyasn1/blob/master/pyasn1/codec/ber/decoder.py#L102). But I guess this decoder is used for other options too - so one would need to add a new CounterDecoder, which looks quite like an IntegerDecoder but uses `signed = False`.

**Comment by etingof** [comment]
Given many apps relying on this decoder, I suspect it's rather a malformed serialization issue. But I need to look to figure that out for sure.

Meanwhile, here's the [authoritative source](http://asn1-playground.oss.com/) of proper encoding, you may want to feed it your integer blob to see how it recovers it. ;-)

**Comment by prauscher** [comment]
Mhh, thank you! I'm really new to the world of ASN1 - I'll submit a seperate issue at the snmpd responsible for this...

**Comment by mczp** [comment]
The issue got solved in mini-snmpd, I think this issue can be closed.
