### ISSUE TITLE
pycryptodome issue

### ISSUE THREAD

**Issue by Costya-Y** [etingof/pysnmp#81]
Hello,

It appears that one of pysnmp dependencies package pycryptodome overwrites pycrypto folder in site-packages, and makes some other libraries crash because of that.

It looks like pycryptodome developers is aware of this issue and have released pycryptodomex library with the same release version with fix for it's structure.
https://pypi.python.org/pypi/pycryptodomex

Please clarify is it possible to move from pycryptodome to pycryptodomex? Codewise it's completely similar, except the main folder.

Thank you,
Costya

**Comment by etingof** [comment]
Thank for raising this issue!

I believe it should not be a problem to switch pysnmp over to pycryptodomex.

Can you point out a link where I could find out the differences between pycryptodome and pycryptodomex? Quick googling does not reveal that to me. %-\

**Comment by Costya-Y** [comment]
Hi, 

Sure.
https://pypi.python.org/pypi/pycryptodomex
in the link above they stated:
the pycryptodomex project is an equivalent library that works under the 'Cryptodome' package.
Also, there is a mentioning on their official site:
https://www.pycryptodome.org/en/latest/src/installation.html?highlight=pycryptodomex

Thank you,
Costya

**Comment by etingof** [comment]
Changed in master (commit 82e59461016e8c0608aeec05489385ec4c18479a).

Thank you!

**Comment by Costya-Y** [comment]
Thanks a lot!
