### ISSUE TITLE
[PATCH] asyncio cmdgen-s let exceptions fall through to the base event loop; commands hang

### ISSUE THREAD

**Issue by astralblue** [etingof/pysnmp#83]
When an object retrieved by an asyncio cmdgen fails to get resolved and raises `SmiError`, the exception is not caught by the cmdgen's callback and passed to the future, resulting in two things:

- The exception is caught by the asyncio base event loop instead, which reports it on the standard error;
- The original caller of the cmdgen hangs forever, because the cmdgen's future is left unmet.

PR #82 fixes this issue.

**Comment by etingof** [comment]
Fixed by #82 merge. Thank you!
