### ISSUE TITLE
[PATCH] ObjectType.resolveWithMib() has OID detection logic reversed; breaks NetworkAddress() value resolution.

### ISSUE THREAD

**Issue by astralblue** [etingof/pysnmp#89]
Commit 9feb2210397a9e81528df3428e47ea4548731e3c introduced an OID-value-to-`ObjectIdentity` resolution logic, but it checks the type in the wrong order: Instead of checking whether the value is of a subtype of OID, it checks whether the value is a *supertype* of OID.  This breaks resolution of `NetworkAddress` values, because `NetworkAddress` is an untagged `Choice` type, and counts as a supertype of OID.

**Comment by astralblue** [comment]
#90 fixes this.

**Comment by astralblue** [comment]
It largely went undetected so far because the check correctly weeds out most tagged simple types, because the tag set of one simple type is neither a subset nor a superset of the tag set of another simple type….  `NetworkAddress` changed that.  😄

**Comment by etingof** [comment]
Merged. Thank you!
