### ISSUE TITLE
Documentation - Code typo

### ISSUE THREAD

**Issue by MGough** [etingof/pysnmp#96]
In the section on enabling the debugging output using different flags (pysnmp/docs/source/examples/contents.rst) there is a code snippet which contains a flag 'secmode' which is not a valid flag.

This should be changed to 'secmod'.

**Comment by etingof** [comment]
Thank you for noting!

Fixed in master and [on-line](http://pysnmp.sourceforge.net/examples/contents.html#using-these-examples).
